# ====================================================================
# scpm (PowerShell Script Profile Manager)
# Module: scpm.psm1
# ====================================================================

$Script:ScpmVersion = "1.0.1"
$Script:ScpmHome = Join-Path $HOME ".scpm"
$Script:ConfigFile = Join-Path $Script:ScpmHome "config.json"
$Script:RegistryFile = Join-Path $Script:ScpmHome "registry.json"
$Script:LoaderFile = Join-Path $Script:ScpmHome "loader.ps1"

# --------------------------------------------------------------------
# 基础辅助函数 (Internal Helpers)
# --------------------------------------------------------------------

function Get-ScpmConfigInternal {
    if (Test-Path -LiteralPath $Script:ConfigFile) {
        try {
            $raw = [System.IO.File]::ReadAllText($Script:ConfigFile, [System.Text.Encoding]::UTF8).TrimStart([char]0xfeff)
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                return ConvertFrom-Json $raw
            }
        } catch {
            Write-Warning "[scpm] 读取 config.json 失败: $($_.Exception.Message)"
        }
    }
    return $null
}

function Save-ScpmConfigInternal([object]$config) {
    if (-not (Test-Path -LiteralPath $Script:ScpmHome)) {
        New-Item -ItemType Directory -Path $Script:ScpmHome -Force | Out-Null
    }
    $json = $config | ConvertTo-Json -Depth 10
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Script:ConfigFile, $json, $utf8NoBom)
}

function Get-ScpmRegistryInternal {
    if (Test-Path -LiteralPath $Script:RegistryFile) {
        try {
            $raw = [System.IO.File]::ReadAllText($Script:RegistryFile, [System.Text.Encoding]::UTF8).TrimStart([char]0xfeff)
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                $obj = ConvertFrom-Json $raw
                if ($null -ne $obj) { return $obj }
            }
        } catch {
            Write-Warning "[scpm] 读取 registry.json 失败: $($_.Exception.Message)"
        }
    }
    return [PSCustomObject]@{
        version = $Script:ScpmVersion
        scripts = [PSCustomObject]@{}
    }
}

function Save-ScpmRegistryInternal([object]$reg) {
    if (-not (Test-Path -LiteralPath $Script:ScpmHome)) {
        New-Item -ItemType Directory -Path $Script:ScpmHome -Force | Out-Null
    }
    $json = $reg | ConvertTo-Json -Depth 10
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Script:RegistryFile, $json, $utf8NoBom)
}

function ConvertTo-PortablePath([string]$absolutePath) {
    if ([string]::IsNullOrWhiteSpace($absolutePath)) { return $absolutePath }
    $normalizedHome = $HOME.TrimEnd('\', '/')
    if ($absolutePath.StartsWith($normalizedHome, [System.StringComparison]::OrdinalIgnoreCase)) {
        $sub = $absolutePath.Substring($normalizedHome.Length).TrimStart('\', '/')
        return "`$HOME\$sub"
    }
    return $absolutePath
}

function Resolve-PortablePathInternal([string]$portablePath) {
    if ([string]::IsNullOrWhiteSpace($portablePath)) { return $portablePath }
    if ($portablePath.StartsWith('$HOME\', [System.StringComparison]::OrdinalIgnoreCase) -or $portablePath.StartsWith('$HOME/', [System.StringComparison]::OrdinalIgnoreCase)) {
        $sub = $portablePath.Substring(6)
        return (Join-Path $HOME $sub)
    }
    if ($portablePath.StartsWith('~\', [System.StringComparison]::OrdinalIgnoreCase) -or $portablePath.StartsWith('~/', [System.StringComparison]::OrdinalIgnoreCase)) {
        $sub = $portablePath.Substring(2)
        return (Join-Path $HOME $sub)
    }
    return $portablePath
}

function Update-ScpmLoaderInternal {
    $reg = Get-ScpmRegistryInternal
    $config = Get-ScpmConfigInternal
    
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("# ====================================================================")
    [void]$sb.AppendLine("# This file is auto-generated by scpm (PowerShell Script Profile Manager).")
    [void]$sb.AppendLine("# Do not edit this file directly. Changes will be overwritten.")
    [void]$sb.AppendLine("# Generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("# ====================================================================")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("# Ensure scpm CLI is always available")
    [void]$sb.AppendLine("if (-not (Get-Command scpm -ErrorAction SilentlyContinue)) {")
    [void]$sb.AppendLine("    `$__scpmPsm1 = Join-Path `$HOME '.scpm\scpm.psm1'")
    [void]$sb.AppendLine("    if (Test-Path -LiteralPath `$__scpmPsm1) {")
    [void]$sb.AppendLine("        Import-Module `$__scpmPsm1 -DisableNameChecking -ErrorAction SilentlyContinue")
    [void]$sb.AppendLine("    }")
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine("")

    $enabledCount = 0
    if ($reg.PSObject.Properties["scripts"]) {
        foreach ($prop in $reg.scripts.PSObject.Properties) {
            $item = $prop.Value
            if ($item.enabled -eq $true) {
                $enabledCount++
                $pPath = $item.path
                $desc = $item.description
                if (-not [string]::IsNullOrWhiteSpace($desc)) {
                    [void]$sb.AppendLine("# [$($item.name)] $desc")
                } else {
                    [void]$sb.AppendLine("# [$($item.name)]")
                }
                
                if ($pPath.StartsWith('$HOME\', [System.StringComparison]::OrdinalIgnoreCase)) {
                    $rel = $pPath.Substring(6).Replace("'", "''")
                    [void]$sb.AppendLine("`$__s = Join-Path `$HOME '$rel'")
                    [void]$sb.AppendLine("if (Test-Path -LiteralPath `$__s) { . `$__s }")
                } else {
                    $escaped = $pPath.Replace("'", "''")
                    [void]$sb.AppendLine("if (Test-Path -LiteralPath '$escaped') { . '$escaped' }")
                }
                [void]$sb.AppendLine("")
            }
        }
    }

    if ($enabledCount -eq 0) {
        [void]$sb.AppendLine("# (No scripts currently enabled)")
    }

    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Script:LoaderFile, $sb.ToString(), $utf8Bom)
    return $enabledCount
}

function Detect-NutstoreCandidates {
    $candidates = [System.Collections.Generic.List[string]]::new()
    
    $potentialBases = @(
        (Join-Path $HOME "Nutstore\1\我的坚果云"),
        (Join-Path $HOME "Nutstore\我的坚果云"),
        "F:\我的坚果云"
    )

    foreach ($b in $potentialBases) {
        if (Test-Path -LiteralPath $b) {
            $scriptsSub = Join-Path $b "scripts"
            if (-not $candidates.Contains($scriptsSub)) {
                $candidates.Add($scriptsSub)
            }
        }
    }
    return $candidates
}

function Extract-ScriptSynopsisInternal([string]$filePath) {
    if (-not (Test-Path -LiteralPath $filePath)) { return "" }
    try {
        $lines = Get-Content -LiteralPath $filePath -TotalCount 35 -ErrorAction SilentlyContinue
        for ($i = 0; $i -lt $lines.Count; $i++) {
            $line = $lines[$i].Trim()
            if ($line -match '^\.SYNOPSIS\s*(.*)$') {
                if (-not [string]::IsNullOrWhiteSpace($matches[1])) { return $matches[1].Trim() }
                if ($i + 1 -lt $lines.Count) { return $lines[$i + 1].Trim() }
            }
            if ($line -match '^#\s*description:\s*(.*)$' -or $line -match '^#\s*简介[：:]\s*(.*)$' -or $line -match '^#\s*(.*CLI.*模式切换.*)$') {
                return $matches[1].Trim()
            }
        }
    } catch {}
    return ""
}

# --------------------------------------------------------------------
# 核心业务命令实现
# --------------------------------------------------------------------

function Invoke-ScpmInit {
    $StoragePath = ""
    $Force = $false
    for ($i = 0; $i -lt $args.Count; $i++) {
        $curr = $args[$i]
        if ($curr -in @("-StoragePath", "-p", "--path") -and ($i + 1 -lt $args.Count)) {
            $StoragePath = $args[++$i]
        } elseif ($curr -in @("-Force", "-f", "--force")) {
            $Force = $true
        } elseif (-not $StoragePath) {
            $StoragePath = $curr
        }
    }

    Write-Host "`n=== [scpm] PowerShell 脚本管理器初始化向导 ===" -ForegroundColor Cyan
    
    $existingConfig = Get-ScpmConfigInternal
    if ($null -ne $existingConfig -and (-not $Force)) {
        Write-Host "检测到已存在的配置: $($existingConfig.storagePath)" -ForegroundColor Yellow
        $reinit = Read-Host "是否重新初始化？(y/N)"
        if ($reinit.Trim().ToLower() -ne "y") {
            Write-Host "已取消初始化。" -ForegroundColor Gray
            return
        }
    }

    # 1. 探测坚果云路径
    $nutstoreDirs = Detect-NutstoreCandidates
    $selectedPath = ""

    if (-not [string]::IsNullOrWhiteSpace($StoragePath)) {
        $selectedPath = $StoragePath
    } else {
        Write-Host "`n[步骤 1/3] 选择脚本存储目录：" -ForegroundColor Green
        $options = [System.Collections.Generic.List[string]]::new()
        
        $idx = 1
        foreach ($cand in $nutstoreDirs) {
            $displayPath = ConvertTo-PortablePath $cand
            Write-Host "  [$idx] 坚果云云同步目录 (推荐): $displayPath" -ForegroundColor Yellow
            $options.Add($cand)
            $idx++
        }

        $localDefault = Join-Path $Script:ScpmHome "scripts"
        $displayLocal = ConvertTo-PortablePath $localDefault
        Write-Host "  [$idx] 本地默认目录: $displayLocal" -ForegroundColor White
        $options.Add($localDefault)
        $idx++

        Write-Host "  [$idx] 自定义绝对路径" -ForegroundColor White
        $customIdx = $idx

        $promptText = "请选择目录 [1-$customIdx] (默认 1): "
        $choice = Read-Host $promptText
        if ([string]::IsNullOrWhiteSpace($choice)) { $choice = "1" }

        $num = 0
        if ([int]::TryParse($choice, [ref]$num) -and $num -ge 1 -and $num -le $options.Count) {
            $selectedPath = $options[$num - 1]
        } elseif ($num -eq $customIdx) {
            $inputPath = Read-Host "请输入自定义存储路径"
            if ([string]::IsNullOrWhiteSpace($inputPath)) {
                $selectedPath = $options[0]
            } else {
                $selectedPath = $inputPath.Trim()
            }
        } else {
            $selectedPath = $options[0]
        }
    }

    # 解析和创建存储目录
    $selectedPath = Resolve-PortablePathInternal $selectedPath
    if (-not (Test-Path -LiteralPath $selectedPath)) {
        New-Item -ItemType Directory -Path $selectedPath -Force | Out-Null
        Write-Host "已创建脚本存储目录: $selectedPath" -ForegroundColor Green
    } else {
        Write-Host "使用现有存储目录: $selectedPath" -ForegroundColor Green
    }

    # 2. 注入 Profile 引导钩子
    Write-Host "`n[步骤 2/3] 配置 PowerShell Profile 注入引导..." -ForegroundColor Green
    $profilesToHook = @(
        (Join-Path $HOME "Documents\PowerShell\Microsoft.PowerShell_profile.ps1"),
        (Join-Path $HOME "Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1")
    )

    $hookBlock = @'
# >>> scpm loader start >>>
$scpmLoader = Join-Path $HOME ".scpm\loader.ps1"
if (Test-Path -LiteralPath $scpmLoader) { . $scpmLoader }
# <<< scpm loader end <<<
'@

    foreach ($pf in $profilesToHook) {
        $pfDir = Split-Path $pf -Parent
        if (-not (Test-Path -LiteralPath $pfDir)) {
            New-Item -ItemType Directory -Path $pfDir -Force | Out-Null
        }

        $existingContent = ""
        if (Test-Path -LiteralPath $pf) {
            $existingContent = [System.IO.File]::ReadAllText($pf, [System.Text.Encoding]::UTF8)
        }

        # 清理旧的手动引用或旧 hook
        $newContent = $existingContent
        if ($newContent -match '(?ms)# >>> scpm loader start >>>.*?# <<< scpm loader end <<<') {
            $newContent = [System.Text.RegularExpressions.Regex]::Replace($newContent, '(?ms)# >>> scpm loader start >>>.*?# <<< scpm loader end <<<(\r?\n)?', '')
        }
        
        if ($newContent -match '(?ms)# agy \(Antigravity CLI\) 模式切换.*?if \(Test-Path -LiteralPath \$agyScript\) \{ \. \$agyScript \}(\r?\n)?') {
            $newContent = [System.Text.RegularExpressions.Regex]::Replace($newContent, '(?ms)# agy \(Antigravity CLI\) 模式切换.*?if \(Test-Path -LiteralPath \$agyScript\) \{ \. \$agyScript \}(\r?\n)?', '')
        }

        $newContent = $newContent.TrimEnd() + "`n`n" + $hookBlock + "`n"
        $utf8Bom = New-Object System.Text.UTF8Encoding($true)
        [System.IO.File]::WriteAllText($pf, $newContent, $utf8Bom)
        
        $relPf = ConvertTo-PortablePath $pf
        Write-Host "  [✓] 已注入 Hook: $relPf" -ForegroundColor Green
    }

    # 3. 扫描并自动导入现有脚本
    Write-Host "`n[步骤 3/3] 扫描并导入脚本库..." -ForegroundColor Green
    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    $nutstoreBase = Split-Path $selectedPath -Parent
    if (Test-Path -LiteralPath $nutstoreBase) {
        $rootAgy = Join-Path $nutstoreBase "agy-toggle.ps1"
        if ((Test-Path -LiteralPath $rootAgy) -and ($selectedPath -ne $nutstoreBase)) {
            $destAgy = Join-Path $selectedPath "agy-toggle.ps1"
            if (-not (Test-Path -LiteralPath $destAgy)) {
                Copy-Item -LiteralPath $rootAgy -Destination $destAgy -Force
                Write-Host "  [自动收录] 检测到现有坚果云脚本，已收纳至脚本库: agy-toggle.ps1" -ForegroundColor Yellow
            }
        }
    }

    $allScripts = Get-ChildItem -LiteralPath $selectedPath -Filter "*.ps1" -File -ErrorAction SilentlyContinue
    $importedCount = 0
    foreach ($file in $allScripts) {
        $name = $file.Name
        if (-not $reg.scripts.PSObject.Properties[$name]) {
            $desc = Extract-ScriptSynopsisInternal $file.FullName
            if ([string]::IsNullOrWhiteSpace($desc)) {
                if ($name -like "*agy*") { $desc = "Antigravity CLI 模式切换与状态管理" }
                else { $desc = "自定义 PowerShell 脚本: $name" }
            }
            $pPath = ConvertTo-PortablePath $file.FullName
            $reg.scripts | Add-Member -NotePropertyName $name -NotePropertyValue ([PSCustomObject]@{
                name = $name
                enabled = $true
                description = $desc
                path = $pPath
                addedAt = (Get-Date -Format "o")
            }) -Force
            Write-Host "  [✓] 已注册并启用: $name ($desc)" -ForegroundColor Green
            $importedCount++
        }
    }

    $configObj = [PSCustomObject]@{
        version = $Script:ScpmVersion
        storagePath = ConvertTo-PortablePath $selectedPath
        profiles = $profilesToHook | ForEach-Object { ConvertTo-PortablePath $_ }
        editor = if (Get-Command code -ErrorAction SilentlyContinue) { "code" } else { "notepad" }
        initializedAt = (Get-Date -Format "o")
    }

    Save-ScpmConfigInternal $configObj
    Save-ScpmRegistryInternal $reg
    $enabled = Update-ScpmLoaderInternal

    Write-Host "`n[成功] scpm 初始化完成！" -ForegroundColor Green
    Write-Host "  - 脚本存储库: $(ConvertTo-PortablePath $selectedPath)" -ForegroundColor Cyan
    Write-Host "  - 已管理脚本: $($reg.scripts.PSObject.Properties.Count) 个 (已启用: $enabled 个)" -ForegroundColor Cyan
    Write-Host "  - 快捷提示: 键入 'scpm list' 查看列表，'scpm help' 查看所有命令。" -ForegroundColor Gray
}

function Invoke-ScpmList {
    [CmdletBinding()]
    param()

    $reg = Get-ScpmRegistryInternal
    $config = Get-ScpmConfigInternal

    Write-Host "`n=== [scpm] 脚本管理清单 ===" -ForegroundColor Cyan
    if ($null -ne $config) {
        Write-Host "存储库路径: $($config.storagePath)`n" -ForegroundColor DarkGray
    }

    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。使用 'scpm add <文件路径>' 或 'scpm new <名称>' 开始添加！" -ForegroundColor Yellow
        return
    }

    $total = 0
    $enabled = 0
    $disabled = 0

    foreach ($prop in $reg.scripts.PSObject.Properties) {
        $item = $prop.Value
        $total++
        $realPath = Resolve-PortablePathInternal $item.path
        $fileExists = Test-Path -LiteralPath $realPath

        $statusMark = if ($item.enabled) {
            $enabled++
            " [✓] "
        } else {
            $disabled++
            " [✗] "
        }
        $statusColor = if ($item.enabled) { "Green" } else { "DarkGray" }

        Write-Host $statusMark -ForegroundColor $statusColor -NoNewline
        Write-Host "$($item.name.PadRight(22))" -ForegroundColor Cyan -NoNewline
        Write-Host "$($item.description)" -ForegroundColor White

        $indent = "       "
        if (-not $fileExists) {
            Write-Host "$indent[文件缺失] $realPath" -ForegroundColor Red
        } else {
            Write-Host "$indent$($item.path)" -ForegroundColor DarkGray
        }
    }

    Write-Host "`n-----------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "总计: $total 个脚本 | 已启用: $enabled | 已禁用: $disabled" -ForegroundColor Gray
    Write-Host "提示: 使用 'scpm enable <名称>' 或 'scpm disable <名称>' 切换注入。" -ForegroundColor DarkGray
}

function Invoke-ScpmEnable {
    $reg = Get-ScpmRegistryInternal
    $updated = $false

    foreach ($rawName in $args) {
        $targetName = if ($rawName.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $rawName } else { "$rawName.ps1" }
        
        $matched = $false
        foreach ($prop in $reg.scripts.PSObject.Properties) {
            if ($prop.Name -like $targetName -or $prop.Name -like $rawName) {
                $matched = $true
                $item = $prop.Value
                if (-not $item.enabled) {
                    $item.enabled = $true
                    $updated = $true
                    Write-Host "[✓] 已启用: $($prop.Name)" -ForegroundColor Green
                    
                    $realPath = Resolve-PortablePathInternal $item.path
                    if (Test-Path -LiteralPath $realPath) {
                        try {
                            . $realPath
                            Write-Host "    已即时载入当前终端会话。" -ForegroundColor Gray
                        } catch {
                            Write-Warning "    即时载入失败: $($_.Exception.Message)"
                        }
                    }
                } else {
                    Write-Host "[提示] $($prop.Name) 已经是启用状态。" -ForegroundColor Yellow
                }
            }
        }

        if (-not $matched) {
            Write-Host "[错误] 未找到名为 '$rawName' 的脚本。" -ForegroundColor Red
        }
    }

    if ($updated) {
        Save-ScpmRegistryInternal $reg
        Update-ScpmLoaderInternal | Out-Null
    }
}

function Invoke-ScpmDisable {
    $reg = Get-ScpmRegistryInternal
    $updated = $false

    foreach ($rawName in $args) {
        $targetName = if ($rawName.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $rawName } else { "$rawName.ps1" }
        
        $matched = $false
        foreach ($prop in $reg.scripts.PSObject.Properties) {
            if ($prop.Name -like $targetName -or $prop.Name -like $rawName) {
                $matched = $true
                $item = $prop.Value
                if ($item.enabled) {
                    $item.enabled = $false
                    $updated = $true
                    Write-Host "[✗] 已禁用: $($prop.Name) (将在下次新开会话生效)" -ForegroundColor Yellow
                } else {
                    Write-Host "[提示] $($prop.Name) 已经是禁用状态。" -ForegroundColor Gray
                }
            }
        }

        if (-not $matched) {
            Write-Host "[错误] 未找到名为 '$rawName' 的脚本。" -ForegroundColor Red
        }
    }

    if ($updated) {
        Save-ScpmRegistryInternal $reg
        Update-ScpmLoaderInternal | Out-Null
    }
}

function Invoke-ScpmAdd {
    $Path = ""
    $Name = ""
    $Desc = ""
    $NoCopy = $false
    $Disable = $false

    for ($i = 0; $i -lt $args.Count; $i++) {
        $curr = $args[$i]
        if ($curr -in @("-Name", "-n", "--name") -and ($i + 1 -lt $args.Count)) {
            $Name = $args[++$i]
        } elseif ($curr -in @("-Desc", "-d", "--desc") -and ($i + 1 -lt $args.Count)) {
            $Desc = $args[++$i]
        } elseif ($curr -in @("-NoCopy", "--no-copy")) {
            $NoCopy = $true
        } elseif ($curr -in @("-Disable", "--disable")) {
            $Disable = $true
        } elseif (-not $Path) {
            $Path = $curr
        }
    }

    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Host "[错误] 指定的文件不存在: $Path" -ForegroundColor Red
        return
    }

    $config = Get-ScpmConfigInternal
    if ($null -eq $config) {
        Write-Host "[错误] scpm 尚未初始化，请先运行 'scpm init'。" -ForegroundColor Red
        return
    }

    $sourceItem = Get-Item -LiteralPath $Path
    $targetName = if (-not [string]::IsNullOrWhiteSpace($Name)) {
        if ($Name.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $Name } else { "$Name.ps1" }
    } else {
        $sourceItem.Name
    }

    $storageDir = Resolve-PortablePathInternal $config.storagePath
    $destPath = Join-Path $storageDir $targetName

    if ((-not $NoCopy) -and ($sourceItem.FullName -ne $destPath)) {
        Copy-Item -LiteralPath $sourceItem.FullName -Destination $destPath -Force
        Write-Host "[文件] 已拷贝到脚本仓库: $destPath" -ForegroundColor Gray
        $finalPath = $destPath
    } else {
        $finalPath = $sourceItem.FullName
    }

    if ([string]::IsNullOrWhiteSpace($Desc)) {
        $Desc = Extract-ScriptSynopsisInternal $finalPath
        if ([string]::IsNullOrWhiteSpace($Desc)) {
            $Desc = "自定义脚本: $targetName"
        }
    }

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    $reg.scripts | Add-Member -NotePropertyName $targetName -NotePropertyValue ([PSCustomObject]@{
        name = $targetName
        enabled = (-not $Disable)
        description = $Desc
        path = ConvertTo-PortablePath $finalPath
        addedAt = (Get-Date -Format "o")
    }) -Force

    Save-ScpmRegistryInternal $reg
    Update-ScpmLoaderInternal | Out-Null

    $statusStr = if (-not $Disable) { "并已启用注入" } else { "处于禁用状态" }
    Write-Host "[成功] 脚本 '$targetName' 已添加成功 ($statusStr)！" -ForegroundColor Green
}

function Invoke-ScpmNew {
    $Name = ""
    $Desc = ""
    $NoEdit = $false

    for ($i = 0; $i -lt $args.Count; $i++) {
        $curr = $args[$i]
        if ($curr -in @("-Desc", "-d", "--desc") -and ($i + 1 -lt $args.Count)) {
            $Desc = $args[++$i]
        } elseif ($curr -in @("-NoEdit", "-n", "--no-edit")) {
            $NoEdit = $true
        } elseif (-not $Name) {
            $Name = $curr
        }
    }

    $config = Get-ScpmConfigInternal
    if ($null -eq $config) {
        Write-Host "[错误] scpm 尚未初始化，请先运行 'scpm init'。" -ForegroundColor Red
        return
    }

    $targetName = if ($Name.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $Name } else { "$Name.ps1" }
    $storageDir = Resolve-PortablePathInternal $config.storagePath
    $targetFile = Join-Path $storageDir $targetName

    if (Test-Path -LiteralPath $targetFile) {
        Write-Host "[错误] 脚本 '$targetName' 已存在于存储目录中。" -ForegroundColor Red
        return
    }

    if ([string]::IsNullOrWhiteSpace($Desc)) {
        $Desc = "PowerShell 脚本 $targetName"
    }

    $fnName = [System.IO.Path]::GetFileNameWithoutExtension($targetName)

    $template = @"
<#
.SYNOPSIS
    $Desc
.DESCRIPTION
    由 scpm (PowerShell Script Profile Manager) 创建
#>

function $fnName {
    [CmdletBinding()]
    param()
    
    Write-Host "[$fnName] 脚本正在运行..." -ForegroundColor Green
}
"@

    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($targetFile, $template, $utf8Bom)

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    $reg.scripts | Add-Member -NotePropertyName $targetName -NotePropertyValue ([PSCustomObject]@{
        name = $targetName
        enabled = $true
        description = $Desc
        path = ConvertTo-PortablePath $targetFile
        addedAt = (Get-Date -Format "o")
    }) -Force

    Save-ScpmRegistryInternal $reg
    Update-ScpmLoaderInternal | Out-Null

    Write-Host "[成功] 已创建新脚本: $targetName (默认启用)" -ForegroundColor Green

    if (-not $NoEdit) {
        Invoke-ScpmEdit $targetName
    }
}

function Invoke-ScpmEdit {
    $targetName = if ($args[0].EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $args[0] } else { "$($args[0]).ps1" }
    $reg = Get-ScpmRegistryInternal

    $foundItem = $null
    foreach ($prop in $reg.scripts.PSObject.Properties) {
        if ($prop.Name -like $targetName -or $prop.Name -like $args[0]) {
            $foundItem = $prop.Value
            break
        }
    }

    if ($null -eq $foundItem) {
        Write-Host "[错误] 未找到脚本: $($args[0])" -ForegroundColor Red
        return
    }

    $realPath = Resolve-PortablePathInternal $foundItem.path
    if (-not (Test-Path -LiteralPath $realPath)) {
        Write-Host "[错误] 脚本文件不存在: $realPath" -ForegroundColor Red
        return
    }

    if (Get-Command code -ErrorAction SilentlyContinue) {
        Start-Process "code" -ArgumentList "`"$realPath`""
    } else {
        Start-Process "notepad.exe" -ArgumentList "`"$realPath`""
    }
    Write-Host "[编辑] 已用编辑器打开: $realPath" -ForegroundColor Gray
}

function Invoke-ScpmRemove {
    $Name = ""
    $DeleteFile = $false

    foreach ($curr in $args) {
        if ($curr -in @("-DeleteFile", "-Delete", "-d", "--delete")) {
            $DeleteFile = $true
        } elseif (-not $Name) {
            $Name = $curr
        }
    }

    $reg = Get-ScpmRegistryInternal
    $targetName = if ($Name.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $Name } else { "$Name.ps1" }

    $toRemove = $null
    $filePath = ""
    foreach ($prop in $reg.scripts.PSObject.Properties) {
        if ($prop.Name -eq $targetName -or $prop.Name -eq $Name) {
            $toRemove = $prop.Name
            $filePath = Resolve-PortablePathInternal $prop.Value.path
            break
        }
    }

    if ($null -eq $toRemove) {
        Write-Host "[错误] 未在管理列表中找到: $Name" -ForegroundColor Red
        return
    }

    $reg.scripts.PSObject.Properties.Remove($toRemove)
    Save-ScpmRegistryInternal $reg
    Update-ScpmLoaderInternal | Out-Null
    Write-Host "[✓] 已从管理清单注销: $toRemove" -ForegroundColor Green

    if ($DeleteFile -and (Test-Path -LiteralPath $filePath)) {
        Remove-Item -LiteralPath $filePath -Force
        Write-Host "    [已删除物理文件] $filePath" -ForegroundColor Yellow
    }
}

function Invoke-ScpmSync {
    [CmdletBinding()]
    param()

    $config = Get-ScpmConfigInternal
    if ($null -eq $config) {
        Write-Host "[错误] scpm 尚未初始化。" -ForegroundColor Red
        return
    }

    $storageDir = Resolve-PortablePathInternal $config.storagePath
    if (-not (Test-Path -LiteralPath $storageDir)) {
        Write-Host "[错误] 存储目录不存在: $storageDir" -ForegroundColor Red
        return
    }

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    Write-Host "`n=== [scpm] 正在同步存储库 ===`n" -ForegroundColor Cyan
    $files = Get-ChildItem -LiteralPath $storageDir -Filter "*.ps1" -File

    $added = 0
    foreach ($f in $files) {
        if (-not $reg.scripts.PSObject.Properties[$f.Name]) {
            $desc = Extract-ScriptSynopsisInternal $f.FullName
            if ([string]::IsNullOrWhiteSpace($desc)) { $desc = "自定义脚本: $($f.Name)" }
            $pPath = ConvertTo-PortablePath $f.FullName

            $reg.scripts | Add-Member -NotePropertyName $f.Name -NotePropertyValue ([PSCustomObject]@{
                name = $f.Name
                enabled = $true
                description = $desc
                path = $pPath
                addedAt = (Get-Date -Format "o")
            }) -Force
            Write-Host "  [发现新脚本] 已添加并启用: $($f.Name) ($desc)" -ForegroundColor Green
            $added++
        }
    }

    # 检查缺失
    $missing = 0
    foreach ($prop in $reg.scripts.PSObject.Properties) {
        $p = Resolve-PortablePathInternal $prop.Value.path
        if (-not (Test-Path -LiteralPath $p)) {
            Write-Host "  [警告] 脚本文件缺失: $($prop.Name) ($p)" -ForegroundColor Yellow
            $missing++
        }
    }

    Save-ScpmRegistryInternal $reg
    $enabled = Update-ScpmLoaderInternal
    Write-Host "`n同步完毕: 新增 $added 个脚本，文件缺失 $missing 个，当前共启用 $enabled 个。" -ForegroundColor Gray
}

function Invoke-ScpmDoctor {
    [CmdletBinding()]
    param()

    Write-Host "`n=== [scpm] 环境健康检查与体检报告 ===" -ForegroundColor Cyan
    
    # 1. 核心目录与配置
    Write-Host "`n[1/4] 配置与元数据状态" -ForegroundColor Green
    if (Test-Path -LiteralPath $Script:ConfigFile) {
        Write-Host "  [✓] 配置文件正常: $Script:ConfigFile" -ForegroundColor Green
    } else {
        Write-Host "  [✗] 配置文件不存在 (请运行 scpm init)" -ForegroundColor Red
    }

    if (Test-Path -LiteralPath $Script:RegistryFile) {
        Write-Host "  [✓] 注册表文件正常: $Script:RegistryFile" -ForegroundColor Green
    } else {
        Write-Host "  [✗] 注册表文件不存在" -ForegroundColor Red
    }

    # 2. 存储库可达性
    Write-Host "`n[2/4] 存储库可达性与坚果云同步" -ForegroundColor Green
    $config = Get-ScpmConfigInternal
    if ($null -ne $config) {
        $realStorage = Resolve-PortablePathInternal $config.storagePath
        if (Test-Path -LiteralPath $realStorage) {
            $isNutstore = $realStorage -like "*Nutstore*" -or $realStorage -like "*坚果云*"
            $tag = if ($isNutstore) { "[坚果云云同步]" } else { "[本地目录]" }
            Write-Host "  [✓] 存储库路径正常 ${tag}: $realStorage" -ForegroundColor Green
        } else {
            Write-Host "  [✗] 存储库路径无法访问: $realStorage" -ForegroundColor Red
        }
    } else {
        Write-Host "  [!] 暂无配置信息" -ForegroundColor Yellow
    }

    # 3. Profile 钩子状态
    Write-Host "`n[3/4] PowerShell Profile 注入检查" -ForegroundColor Green
    $profiles = @(
        @{ Name = "PowerShell 7"; Path = (Join-Path $HOME "Documents\PowerShell\Microsoft.PowerShell_profile.ps1") },
        @{ Name = "Windows PowerShell 5.1"; Path = (Join-Path $HOME "Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1") }
    )

    foreach ($pf in $profiles) {
        if (Test-Path -LiteralPath $pf.Path) {
            $content = [System.IO.File]::ReadAllText($pf.Path, [System.Text.Encoding]::UTF8)
            if ($content -match 'scpm loader start') {
                Write-Host "  [✓] $($pf.Name): 已挂载 scpm loader" -ForegroundColor Green
            } else {
                Write-Host "  [!] $($pf.Name): 尚未注入 loader 钩子 (可执行 scpm init 自动挂载)" -ForegroundColor Yellow
            }
        } else {
            Write-Host "  [!] $($pf.Name): Profile 文件不存在" -ForegroundColor DarkGray
        }
    }

    # 4. 脚本完整度
    Write-Host "`n[4/4] 脚本健康度检查" -ForegroundColor Green
    $reg = Get-ScpmRegistryInternal
    $valid = 0
    $broken = 0
    foreach ($prop in $reg.scripts.PSObject.Properties) {
        $real = Resolve-PortablePathInternal $prop.Value.path
        if (Test-Path -LiteralPath $real) {
            $valid++
        } else {
            $broken++
            Write-Host "  [✗] 缺失文件: $($prop.Name) -> $real" -ForegroundColor Red
        }
    }
    if ($broken -eq 0) {
        Write-Host "  [✓] 所有已登记脚本文件完整 ($valid/$valid)" -ForegroundColor Green
    }

    Write-Host "`n检查完成！" -ForegroundColor Cyan
}

function Invoke-ScpmUpdate {
    $Force = $false
    foreach ($curr in $args) {
        if ($curr -in @("-Force", "-f", "--force")) {
            $Force = $true
        }
    }

    Write-Host "`n=== [scpm] 正在检查更新... ===" -ForegroundColor Cyan
    $repoBase = "https://raw.githubusercontent.com/hbhszy/scpm/main/src"
    $psd1Url = "$repoBase/scpm.psd1"
    $psm1Url = "$repoBase/scpm.psm1"

    try {
        Write-Host "正在连接 GitHub 检查最新版本..." -ForegroundColor Gray
        $wc = New-Object System.Net.WebClient
        $wc.Encoding = [System.Text.Encoding]::UTF8
        
        $remotePsd1 = $wc.DownloadString($psd1Url)
        $remoteVer = "1.0.1"
        if ($remotePsd1 -match "ModuleVersion\s*=\s*['""]([^'""]+)['""]") {
            $remoteVer = $matches[1]
        }

        Write-Host "当前版本: v$Script:ScpmVersion | 远程版本: v$remoteVer" -ForegroundColor White
        
        if ($remoteVer -le $Script:ScpmVersion -and (-not $Force)) {
            Write-Host "[✓] 当前已经是最新版本 (v$Script:ScpmVersion)。如需强制重装可运行: sm update -Force" -ForegroundColor Green
            return
        }

        Write-Host "正在下载更新组件..." -ForegroundColor Yellow
        $remotePsm1 = $wc.DownloadString($psm1Url)

        $utf8Bom = New-Object System.Text.UTF8Encoding($true)
        $targets = @(
            (Join-Path $HOME ".scpm"),
            (Join-Path $HOME "Documents\PowerShell\Modules\scpm"),
            (Join-Path $HOME "Documents\WindowsPowerShell\Modules\scpm")
        )

        foreach ($dir in $targets) {
            if (-not (Test-Path -LiteralPath $dir)) {
                New-Item -ItemType Directory -Path $dir -Force | Out-Null
            }
            [System.IO.File]::WriteAllText((Join-Path $dir "scpm.psm1"), $remotePsm1, $utf8Bom)
            [System.IO.File]::WriteAllText((Join-Path $dir "scpm.psd1"), $remotePsd1, $utf8Bom)
        }

        Update-ScpmLoaderInternal | Out-Null
        Import-Module (Join-Path $HOME ".scpm\scpm.psm1") -Force -DisableNameChecking -ErrorAction SilentlyContinue

        Write-Host "[✓] scpm 成功更新至 v$remoteVer！已即时载入当前会话。" -ForegroundColor Green
    } catch {
        Write-Host "[scpm] 更新检查失败: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "提示: 也可通过一键安装脚本进行重装/升级:" -ForegroundColor Yellow
        Write-Host "  irm https://raw.githubusercontent.com/hbhszy/scpm/main/install.ps1 | iex" -ForegroundColor White
    }
}

# --------------------------------------------------------------------
# 主入口命令: scpm (别名 sm)
# --------------------------------------------------------------------

function scpm {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)]
        [ValidateSet("init", "list", "ls", "enable", "on", "disable", "off", "add", "new", "edit", "remove", "rm", "sync", "refresh", "doctor", "status", "update", "upgrade", "help", "-h", "--help", "")]
        [string]$Subcommand = "list",

        [Parameter(Position = 1, ValueFromRemainingArguments = $true)]
        [string[]]$RemainingArgs
    )

    switch ($Subcommand) {
        "init" {
            Invoke-ScpmInit @RemainingArgs
        }
        { $_ -in @("list", "ls", "") } {
            Invoke-ScpmList
        }
        { $_ -in @("enable", "on") } {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm enable <脚本名称...>" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmEnable @RemainingArgs
        }
        { $_ -in @("disable", "off") } {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm disable <脚本名称...>" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmDisable @RemainingArgs
        }
        "add" {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm add <脚本路径> [-Name <名称>] [-Desc <描述>]" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmAdd @RemainingArgs
        }
        "new" {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm new <脚本名称> [-Desc <描述>]" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmNew @RemainingArgs
        }
        "edit" {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm edit <脚本名称>" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmEdit @RemainingArgs
        }
        { $_ -in @("remove", "rm") } {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm remove <脚本名称> [-DeleteFile]" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmRemove @RemainingArgs
        }
        { $_ -in @("sync", "refresh") } {
            Invoke-ScpmSync
        }
        { $_ -in @("doctor", "status") } {
            Invoke-ScpmDoctor
        }
        { $_ -in @("update", "upgrade") } {
            Invoke-ScpmUpdate @RemainingArgs
        }
        default {
            Write-Host "`n=== scpm (PowerShell Script Profile Manager) v$Script:ScpmVersion ===" -ForegroundColor Cyan
            Write-Host "轻量、零依赖的 PowerShell 脚本与云同步管理器`n" -ForegroundColor White
            Write-Host "常用命令 (别名: sm):" -ForegroundColor Green
            Write-Host "  scpm init                # 初始化向导 (自动探测坚果云、配置 Profile)" -ForegroundColor White
            Write-Host "  scpm list / ls           # 查看所有受管理脚本及启停状态" -ForegroundColor White
            Write-Host "  scpm enable / on <名称>  # 启用脚本注入 (支持通配符)" -ForegroundColor White
            Write-Host "  scpm disable / off <名称># 禁用脚本注入" -ForegroundColor White
            Write-Host "  scpm add <路径>          # 添加现有脚本到存储库" -ForegroundColor White
            Write-Host "  scpm new <名称>          # 创建新脚本模板并打开编辑器" -ForegroundColor White
            Write-Host "  scpm edit <名称>         # 打开编辑脚本" -ForegroundColor White
            Write-Host "  scpm remove / rm <名称>  # 从管理清单移除脚本" -ForegroundColor White
            Write-Host "  scpm sync / refresh      # 同步存储库目录并刷新" -ForegroundColor White
            Write-Host "  scpm doctor / status     # 检查配置、存储库与 Profile 挂载健康度" -ForegroundColor White
            Write-Host "  scpm update / upgrade    # 检查并更新 scpm 至最新版本" -ForegroundColor White
            Write-Host ""
        }
    }
}

# 导出函数与别名
Set-Alias -Name sm -Value scpm -Scope Global
Export-ModuleMember -Function scpm -Alias sm

# --------------------------------------------------------------------
# 自动补全支持 (Argument Completion)
# --------------------------------------------------------------------
try {
    $scriptCompleter = {
        param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

        $elements = $commandAst.CommandElements
        $subcommand = if ($elements.Count -gt 1) { $elements[1].Extent.Text } else { "" }

        if ($elements.Count -eq 2 -and (-not $elements[1].Extent.Text.EndsWith(" "))) {
            $subs = @("init", "list", "ls", "enable", "on", "disable", "off", "add", "new", "edit", "remove", "rm", "sync", "refresh", "doctor", "status", "update", "upgrade", "help")
            $subs | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        } elseif ($subcommand -in @("enable", "on", "disable", "off", "edit", "remove", "rm")) {
            $reg = Get-ScpmRegistryInternal
            if ($null -ne $reg.scripts) {
                $reg.scripts.PSObject.Properties | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Value.description)
                }
            }
        }
    }

    Register-ArgumentCompleter -CommandName ('scpm', 'sm') -ScriptBlock $scriptCompleter -ErrorAction SilentlyContinue
} catch {}
