# ====================================================================
# scpm (PowerShell Script Profile Manager)
# Module: scpm.psm1
# ====================================================================

$Script:ScpmVersion = "1.1.0"
$Script:ScpmHome = Join-Path $HOME ".scpm"
$Script:ConfigFile = Join-Path $Script:ScpmHome "config.json"
$Script:RegistryFile = Join-Path $Script:ScpmHome "registry.json"
$Script:LoaderFile = Join-Path $Script:ScpmHome "loader.ps1"

# --------------------------------------------------------------------
# 基础辅助函数 (Internal Helpers)
# --------------------------------------------------------------------

function Get-ScpmConfigInternal {
    if (Test-Path -LiteralPath $Script:ConfigFile) {
        try {
            $raw = [System.IO.File]::ReadAllText($Script:ConfigFile, [System.Text.Encoding]::UTF8).TrimStart([char]0xfeff)
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                return ConvertFrom-Json $raw
            }
        } catch {
            Write-Warning "[scpm] 读取 config.json 失败: $($_.Exception.Message)"
        }
    }
    return $null
}

function Save-ScpmConfigInternal([object]$config) {
    if (-not (Test-Path -LiteralPath $Script:ScpmHome)) {
        New-Item -ItemType Directory -Path $Script:ScpmHome -Force | Out-Null
    }
    $json = $config | ConvertTo-Json -Depth 10
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Script:ConfigFile, $json, $utf8NoBom)
}

function Get-ScpmRegistryInternal {
    if (Test-Path -LiteralPath $Script:RegistryFile) {
        try {
            $raw = [System.IO.File]::ReadAllText($Script:RegistryFile, [System.Text.Encoding]::UTF8).TrimStart([char]0xfeff)
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                $obj = ConvertFrom-Json $raw
                if ($null -ne $obj) { return $obj }
            }
        } catch {
            Write-Warning "[scpm] 读取 registry.json 失败: $($_.Exception.Message)"
        }
    }
    return [PSCustomObject]@{
        version = $Script:ScpmVersion
        scripts = [PSCustomObject]@{}
    }
}

function Save-ScpmRegistryInternal([object]$reg) {
    if (-not (Test-Path -LiteralPath $Script:ScpmHome)) {
        New-Item -ItemType Directory -Path $Script:ScpmHome -Force | Out-Null
    }
    $json = $reg | ConvertTo-Json -Depth 10
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Script:RegistryFile, $json, $utf8NoBom)
}

function ConvertTo-PortablePath([string]$absolutePath) {
    if ([string]::IsNullOrWhiteSpace($absolutePath)) { return $absolutePath }
    $normalizedHome = $HOME.TrimEnd('\', '/')
    if ($absolutePath.StartsWith($normalizedHome, [System.StringComparison]::OrdinalIgnoreCase)) {
        $sub = $absolutePath.Substring($normalizedHome.Length).TrimStart('\', '/')
        return "`$HOME\$sub"
    }
    return $absolutePath
}

function Resolve-PortablePathInternal([string]$portablePath) {
    if ([string]::IsNullOrWhiteSpace($portablePath)) { return $portablePath }
    if ($portablePath.StartsWith('$HOME\', [System.StringComparison]::OrdinalIgnoreCase) -or $portablePath.StartsWith('$HOME/', [System.StringComparison]::OrdinalIgnoreCase)) {
        $sub = $portablePath.Substring(6)
        return (Join-Path $HOME $sub)
    }
    if ($portablePath.StartsWith('~\', [System.StringComparison]::OrdinalIgnoreCase) -or $portablePath.StartsWith('~/', [System.StringComparison]::OrdinalIgnoreCase)) {
        $sub = $portablePath.Substring(2)
        return (Join-Path $HOME $sub)
    }
    return $portablePath
}

function Update-ScpmLoaderInternal {
    $reg = Get-ScpmRegistryInternal
    $config = Get-ScpmConfigInternal
    
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("# ====================================================================")
    [void]$sb.AppendLine("# This file is auto-generated by scpm (PowerShell Script Profile Manager).")
    [void]$sb.AppendLine("# Do not edit this file directly. Changes will be overwritten.")
    [void]$sb.AppendLine("# Generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("# ====================================================================")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("# Ensure scpm CLI is always available")
    [void]$sb.AppendLine("if (-not (Get-Command scpm -ErrorAction SilentlyContinue)) {")
    [void]$sb.AppendLine("    `$__scpmPsm1 = Join-Path `$HOME '.scpm\scpm.psm1'")
    [void]$sb.AppendLine("    if (Test-Path -LiteralPath `$__scpmPsm1) {")
    [void]$sb.AppendLine("        Import-Module `$__scpmPsm1 -DisableNameChecking -ErrorAction SilentlyContinue")
    [void]$sb.AppendLine("    }")
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine("")

    $enabledCount = 0
    if ($reg.PSObject.Properties["scripts"]) {
        foreach ($prop in $reg.scripts.PSObject.Properties) {
            $item = $prop.Value
            if ($item.enabled -eq $true) {
                $enabledCount++
                $pPath = $item.path
                $desc = $item.description
                if (-not [string]::IsNullOrWhiteSpace($desc)) {
                    [void]$sb.AppendLine("# [$($item.name)] $desc")
                } else {
                    [void]$sb.AppendLine("# [$($item.name)]")
                }
                
                if ($pPath.StartsWith('$HOME\', [System.StringComparison]::OrdinalIgnoreCase)) {
                    $rel = $pPath.Substring(6).Replace("'", "''")
                    [void]$sb.AppendLine("`$__s = Join-Path `$HOME '$rel'")
                    [void]$sb.AppendLine("if (Test-Path -LiteralPath `$__s) { . `$__s }")
                } else {
                    $escaped = $pPath.Replace("'", "''")
                    [void]$sb.AppendLine("if (Test-Path -LiteralPath '$escaped') { . '$escaped' }")
                }
                [void]$sb.AppendLine("")
            }
        }
    }

    if ($enabledCount -eq 0) {
        [void]$sb.AppendLine("# (No scripts currently enabled)")
    }

    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Script:LoaderFile, $sb.ToString(), $utf8Bom)
    return $enabledCount
}

function Detect-NutstoreCandidates {
    $candidates = [System.Collections.Generic.List[string]]::new()
    
    $potentialBases = @(
        (Join-Path $HOME "Nutstore\1\我的坚果云"),
        (Join-Path $HOME "Nutstore\我的坚果云")
    )

    foreach ($b in $potentialBases) {
        if (Test-Path -LiteralPath $b) {
            $scriptsSub = Join-Path $b "scripts"
            if (-not $candidates.Contains($scriptsSub)) {
                $candidates.Add($scriptsSub)
            }
        }
    }
    return $candidates
}

function Extract-ScriptSynopsisInternal([string]$filePath) {
    if (-not (Test-Path -LiteralPath $filePath)) { return "" }
    try {
        $lines = Get-Content -LiteralPath $filePath -TotalCount 35 -ErrorAction SilentlyContinue
        for ($i = 0; $i -lt $lines.Count; $i++) {
            $line = $lines[$i].Trim()
            if ($line -match '^\.SYNOPSIS\s*(.*)$') {
                if (-not [string]::IsNullOrWhiteSpace($matches[1])) { return $matches[1].Trim() }
                if ($i + 1 -lt $lines.Count) { return $lines[$i + 1].Trim() }
            }
            if ($line -match '^#\s*description:\s*(.*)$' -or $line -match '^#\s*简介[：:]\s*(.*)$' -or $line -match '^#\s*(.*CLI.*模式切换.*)$') {
                return $matches[1].Trim()
            }
        }
    } catch {}
    return ""
}

function Get-ScpmScriptMethodsInternal([string]$filePath) {
    $result = [PSCustomObject]@{
        Path = $filePath
        FileExists = $false
        Synopsis = ""
        Description = ""
        Usage = ""
        Functions = [System.Collections.Generic.List[object]]::new()
        Aliases = [System.Collections.Generic.List[object]]::new()
        TopLevelFunctions = [System.Collections.Generic.List[string]]::new()
        Summary = ""
    }

    if (-not (Test-Path -LiteralPath $filePath)) {
        return $result
    }

    $result.FileExists = $true

    try {
        $raw = [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)
    } catch {
        return $result
    }

    # 1. 提取帮助注释 (.SYNOPSIS, .DESCRIPTION, .USAGE)
    if ($raw -match '(?s)\.SYNOPSIS\s*(.*?)(?=\r?\n\s*\.[A-Z]+|\#\>)') {
        $result.Synopsis = $matches[1].Trim()
    }
    if ($raw -match '(?s)\.DESCRIPTION\s*(.*?)(?=\r?\n\s*\.[A-Z]+|\#\>)') {
        $result.Description = $matches[1].Trim()
    }
    if ($raw -match '(?s)\.USAGE\s*(.*?)(?=\r?\n\s*\.[A-Z]+|\#\>)') {
        $result.Usage = $matches[1].Trim()
    }

    # 2. 通过 AST 解析函数与别名
    try {
        $tokens = $null
        $errors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseInput($raw, [ref]$tokens, [ref]$errors)

        if ($null -ne $ast) {
            $funcAsts = $ast.FindAll({ $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
            foreach ($f in $funcAsts) {
                # 检查是否为嵌套函数
                $isNested = $false
                $enclosing = ""
                $parent = $f.Parent
                while ($null -ne $parent) {
                    if ($parent -is [System.Management.Automation.Language.FunctionDefinitionAst]) {
                        $isNested = $true
                        $enclosing = $parent.Name
                        break
                    }
                    $parent = $parent.Parent
                }

                $params = [System.Collections.Generic.List[object]]::new()
                $paramBlock = if ($f.Parameters) { $f.Parameters } elseif ($f.Body.ParamBlock) { $f.Body.ParamBlock.Parameters } else { $null }
                $sigParts = [System.Collections.Generic.List[string]]::new()

                if ($null -ne $paramBlock) {
                    foreach ($p in $paramBlock) {
                        $pName = "$" + $p.Name.VariablePath.UserPath
                        $typeName = if ($p.StaticType -and $p.StaticType.Name -ne "Object") { "[$($p.StaticType.Name)]" } else { "" }
                        $defaultVal = if ($p.DefaultValue) { $p.DefaultValue.Extent.Text } else { "" }

                        $valSet = $p.Attributes | Where-Object { $_.TypeName.Name -in @("ValidateSet", "ValidateSetAttribute") }
                        $valSetOptions = @()
                        if ($valSet) {
                            $valSetOptions = @($valSet.PositionalArguments | ForEach-Object {
                                if ($_ -is [System.Management.Automation.Language.StringConstantExpressionAst]) { $_.Value } else { $_.Extent.Text.Trim("'", '"') }
                            }) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
                        }

                        $params.Add([PSCustomObject]@{
                            Name = $pName
                            Type = $typeName
                            DefaultValue = $defaultVal
                            ValidateSet = $valSetOptions
                        })

                        if ($valSetOptions.Count -gt 0) {
                            $sigParts.Add("[$pName {$($valSetOptions -join ' | ')}]")
                        } elseif (-not [string]::IsNullOrWhiteSpace($defaultVal)) {
                            $sigParts.Add("[$pName = $defaultVal]")
                        } elseif (-not [string]::IsNullOrWhiteSpace($typeName)) {
                            $sigParts.Add("[$typeName$pName]")
                        } else {
                            $sigParts.Add("[$pName]")
                        }
                    }
                }

                $sig = if ($sigParts.Count -gt 0) { "$($f.Name) $($sigParts -join ' ')" } else { $f.Name }

                $funcObj = [PSCustomObject]@{
                    Name = $f.Name
                    IsNested = $isNested
                    Enclosing = $enclosing
                    Parameters = $params
                    Signature = $sig
                    Line = $f.Extent.StartLineNumber
                }
                $result.Functions.Add($funcObj)

                if (-not $isNested) {
                    $result.TopLevelFunctions.Add($f.Name)
                }
            }

            # 解析别名 (Set-Alias / New-Alias)
            $cmdAsts = $ast.FindAll({ $args[0] -is [System.Management.Automation.Language.CommandAst] }, $true)
            foreach ($cmd in $cmdAsts) {
                $cmdName = $cmd.GetCommandName()
                if ($cmdName -in @("Set-Alias", "New-Alias", "sal")) {
                    $aliasName = ""
                    $aliasVal = ""
                    $elements = $cmd.CommandElements
                    for ($i = 1; $i -lt $elements.Count; $i++) {
                        $elemText = $elements[$i].Extent.Text
                        if ($elemText -in @("-Name", "-n") -and ($i + 1 -lt $elements.Count)) {
                            $aliasName = $elements[++$i].Extent.Text.Trim("'", '"')
                        } elseif ($elemText -in @("-Value", "-v") -and ($i + 1 -lt $elements.Count)) {
                            $aliasVal = $elements[++$i].Extent.Text.Trim("'", '"')
                        } elseif (-not $aliasName) {
                            $aliasName = $elemText.Trim("'", '"')
                        } elseif (-not $aliasVal) {
                            $aliasVal = $elemText.Trim("'", '"')
                        }
                    }
                    if (-not [string]::IsNullOrWhiteSpace($aliasName)) {
                        $result.Aliases.Add([PSCustomObject]@{
                            Name = $aliasName
                            Target = $aliasVal
                        })
                    }
                }
            }
        }
    } catch {}

    if ($result.TopLevelFunctions.Count -gt 0) {
        $result.Summary = ($result.TopLevelFunctions -join ", ")
    } elseif ($result.Functions.Count -gt 0) {
        $result.Summary = (($result.Functions | ForEach-Object { $_.Name }) -join ", ")
    } else {
        $result.Summary = "(直接执行脚本文件)"
    }

    return $result
}

function Resolve-ScpmScriptPropsInternal([string]$target, [array]$scriptProps) {
    $results = [System.Collections.Generic.List[object]]::new()
    if ([string]::IsNullOrWhiteSpace($target)) { return $results }

    # 1. 尝试数字序号匹配 (1-based)
    $num = 0
    if ([int]::TryParse($target, [ref]$num) -and $num -ge 1 -and $num -le $scriptProps.Count) {
        $results.Add($scriptProps[$num - 1])
        return $results
    }

    # 2. 尝试名称精确匹配或加 .ps1 匹配
    $withExt = if ($target.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $target } else { "$target.ps1" }
    foreach ($p in $scriptProps) {
        if ($p.Name -eq $target -or $p.Name -eq $withExt) {
            $results.Add($p)
            return $results
        }
    }

    # 3. 尝试通配符或包含匹配
    foreach ($p in $scriptProps) {
        if ($p.Name -like $target -or $p.Name -like "*$target*") {
            if (-not $results.Contains($p)) {
                $results.Add($p)
            }
        }
    }

    return $results
}

function Select-ScpmScriptSingleInteractive([string]$title, [array]$scriptProps) {
    if ($null -eq $scriptProps -or $scriptProps.Count -eq 0) {
        return $null
    }

    Write-Host "`n=== $title ===" -ForegroundColor Cyan
    for ($i = 0; $i -lt $scriptProps.Count; $i++) {
        $p = $scriptProps[$i]
        $st = if ($p.Value.enabled) { "[✓]" } else { "[✗]" }
        $stColor = if ($p.Value.enabled) { "Green" } else { "DarkGray" }
        Write-Host "  [$($i + 1)] " -NoNewline -ForegroundColor White
        Write-Host "$st " -NoNewline -ForegroundColor $stColor
        Write-Host "$($p.Name.PadRight(22))" -NoNewline -ForegroundColor Cyan
        Write-Host "$($p.Value.description)" -ForegroundColor Gray
    }

    $choice = Read-Host "`n请选择脚本编号 [1-$($scriptProps.Count)] (q 退出)"
    if ([string]::IsNullOrWhiteSpace($choice) -or $choice.Trim().ToLower() -in @("q", "quit", "exit")) {
        Write-Host "已取消。" -ForegroundColor Gray
        return $null
    }

    $num = 0
    if ([int]::TryParse($choice.Trim(), [ref]$num) -and $num -ge 1 -and $num -le $scriptProps.Count) {
        return $scriptProps[$num - 1]
    }

    # 尝试按名称查
    $matched = Resolve-ScpmScriptPropsInternal $choice.Trim() $scriptProps
    if ($matched.Count -gt 0) {
        return $matched[0]
    }

    Write-Host "[错误] 无效的编号或名称。" -ForegroundColor Red
    return $null
}

# --------------------------------------------------------------------
# 核心业务命令实现
# --------------------------------------------------------------------

function Invoke-ScpmInit {
    $StoragePath = ""
    $Force = $false
    for ($i = 0; $i -lt $args.Count; $i++) {
        $curr = $args[$i]
        if ($curr -in @("-StoragePath", "-p", "--path") -and ($i + 1 -lt $args.Count)) {
            $StoragePath = $args[++$i]
        } elseif ($curr -in @("-Force", "-f", "--force")) {
            $Force = $true
        } elseif (-not $StoragePath) {
            $StoragePath = $curr
        }
    }

    Write-Host "`n=== [scpm] PowerShell 脚本管理器初始化向导 ===" -ForegroundColor Cyan
    
    $existingConfig = Get-ScpmConfigInternal
    if ($null -ne $existingConfig -and (-not $Force)) {
        Write-Host "检测到已存在的配置: $($existingConfig.storagePath)" -ForegroundColor Yellow
        $reinit = Read-Host "是否重新初始化？(y/N)"
        if ($reinit.Trim().ToLower() -ne "y") {
            Write-Host "已取消初始化。" -ForegroundColor Gray
            return
        }
    }

    # 1. 探测坚果云路径
    $nutstoreDirs = Detect-NutstoreCandidates
    $selectedPath = ""

    if (-not [string]::IsNullOrWhiteSpace($StoragePath)) {
        $selectedPath = $StoragePath
    } else {
        Write-Host "`n[步骤 1/3] 选择脚本存储目录：" -ForegroundColor Green
        $options = [System.Collections.Generic.List[string]]::new()
        
        $idx = 1
        foreach ($cand in $nutstoreDirs) {
            $displayPath = ConvertTo-PortablePath $cand
            Write-Host "  [$idx] 坚果云云同步目录 (推荐): $displayPath" -ForegroundColor Yellow
            $options.Add($cand)
            $idx++
        }

        $localDefault = Join-Path $Script:ScpmHome "scripts"
        $displayLocal = ConvertTo-PortablePath $localDefault
        Write-Host "  [$idx] 本地默认目录: $displayLocal" -ForegroundColor White
        $options.Add($localDefault)
        $idx++

        Write-Host "  [$idx] 自定义绝对路径" -ForegroundColor White
        $customIdx = $idx

        $promptText = "请选择目录 [1-$customIdx] (默认 1): "
        $choice = Read-Host $promptText
        if ([string]::IsNullOrWhiteSpace($choice)) { $choice = "1" }

        $num = 0
        if ([int]::TryParse($choice, [ref]$num) -and $num -ge 1 -and $num -le $options.Count) {
            $selectedPath = $options[$num - 1]
        } elseif ($num -eq $customIdx) {
            $inputPath = Read-Host "请输入自定义存储路径"
            if ([string]::IsNullOrWhiteSpace($inputPath)) {
                $selectedPath = $options[0]
            } else {
                $selectedPath = $inputPath.Trim()
            }
        } else {
            $selectedPath = $options[0]
        }
    }

    # 解析和创建存储目录
    $selectedPath = Resolve-PortablePathInternal $selectedPath
    if (-not (Test-Path -LiteralPath $selectedPath)) {
        New-Item -ItemType Directory -Path $selectedPath -Force | Out-Null
        Write-Host "已创建脚本存储目录: $selectedPath" -ForegroundColor Green
    } else {
        Write-Host "使用现有存储目录: $selectedPath" -ForegroundColor Green
    }

    # 2. 注入 Profile 引导钩子
    Write-Host "`n[步骤 2/3] 配置 PowerShell Profile 注入引导..." -ForegroundColor Green
    $profilesToHook = @(
        (Join-Path $HOME "Documents\PowerShell\Microsoft.PowerShell_profile.ps1"),
        (Join-Path $HOME "Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1")
    )

    $hookBlock = @'
# >>> scpm loader start >>>
$scpmLoader = Join-Path $HOME ".scpm\loader.ps1"
if (Test-Path -LiteralPath $scpmLoader) { . $scpmLoader }
# <<< scpm loader end <<<
'@

    foreach ($pf in $profilesToHook) {
        $pfDir = Split-Path $pf -Parent
        if (-not (Test-Path -LiteralPath $pfDir)) {
            New-Item -ItemType Directory -Path $pfDir -Force | Out-Null
        }

        $existingContent = ""
        if (Test-Path -LiteralPath $pf) {
            $existingContent = [System.IO.File]::ReadAllText($pf, [System.Text.Encoding]::UTF8)
        }

        # 清理旧的手动引用或旧 hook
        $newContent = $existingContent
        if ($newContent -match '(?ms)# >>> scpm loader start >>>.*?# <<< scpm loader end <<<') {
            $newContent = [System.Text.RegularExpressions.Regex]::Replace($newContent, '(?ms)# >>> scpm loader start >>>.*?# <<< scpm loader end <<<(\r?\n)?', '')
        }
        
        if ($newContent -match '(?ms)# agy \(Antigravity CLI\) 模式切换.*?if \(Test-Path -LiteralPath \$agyScript\) \{ \. \$agyScript \}(\r?\n)?') {
            $newContent = [System.Text.RegularExpressions.Regex]::Replace($newContent, '(?ms)# agy \(Antigravity CLI\) 模式切换.*?if \(Test-Path -LiteralPath \$agyScript\) \{ \. \$agyScript \}(\r?\n)?', '')
        }

        $newContent = $newContent.TrimEnd() + "`n`n" + $hookBlock + "`n"
        $utf8Bom = New-Object System.Text.UTF8Encoding($true)
        [System.IO.File]::WriteAllText($pf, $newContent, $utf8Bom)
        
        $relPf = ConvertTo-PortablePath $pf
        Write-Host "  [✓] 已注入 Hook: $relPf" -ForegroundColor Green
    }

    # 3. 扫描并自动导入现有脚本
    Write-Host "`n[步骤 3/3] 扫描并导入脚本库..." -ForegroundColor Green
    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    $nutstoreBase = Split-Path $selectedPath -Parent
    if (Test-Path -LiteralPath $nutstoreBase) {
        $rootAgy = Join-Path $nutstoreBase "agy-toggle.ps1"
        if ((Test-Path -LiteralPath $rootAgy) -and ($selectedPath -ne $nutstoreBase)) {
            $destAgy = Join-Path $selectedPath "agy-toggle.ps1"
            if (-not (Test-Path -LiteralPath $destAgy)) {
                Copy-Item -LiteralPath $rootAgy -Destination $destAgy -Force
                Write-Host "  [自动收录] 检测到现有坚果云脚本，已收纳至脚本库: agy-toggle.ps1" -ForegroundColor Yellow
            }
        }
    }

    $allScripts = Get-ChildItem -LiteralPath $selectedPath -Filter "*.ps1" -File -ErrorAction SilentlyContinue
    $importedCount = 0
    foreach ($file in $allScripts) {
        $name = $file.Name
        if (-not $reg.scripts.PSObject.Properties[$name]) {
            $desc = Extract-ScriptSynopsisInternal $file.FullName
            if ([string]::IsNullOrWhiteSpace($desc)) {
                if ($name -like "*agy*") { $desc = "Antigravity CLI 模式切换与状态管理" }
                else { $desc = "自定义 PowerShell 脚本: $name" }
            }
            $pPath = ConvertTo-PortablePath $file.FullName
            $reg.scripts | Add-Member -NotePropertyName $name -NotePropertyValue ([PSCustomObject]@{
                name = $name
                enabled = $true
                description = $desc
                path = $pPath
                addedAt = (Get-Date -Format "o")
            }) -Force
            Write-Host "  [✓] 已注册并启用: $name ($desc)" -ForegroundColor Green
            $importedCount++
        }
    }

    $configObj = [PSCustomObject]@{
        version = $Script:ScpmVersion
        storagePath = ConvertTo-PortablePath $selectedPath
        profiles = $profilesToHook | ForEach-Object { ConvertTo-PortablePath $_ }
        editor = if (Get-Command code -ErrorAction SilentlyContinue) { "code" } else { "notepad" }
        initializedAt = (Get-Date -Format "o")
    }

    Save-ScpmConfigInternal $configObj
    Save-ScpmRegistryInternal $reg
    $enabled = Update-ScpmLoaderInternal

    Write-Host "`n[成功] scpm 初始化完成！" -ForegroundColor Green
    Write-Host "  - 脚本存储库: $(ConvertTo-PortablePath $selectedPath)" -ForegroundColor Cyan
    Write-Host "  - 已管理脚本: $($reg.scripts.PSObject.Properties.Count) 个 (已启用: $enabled 个)" -ForegroundColor Cyan
    Write-Host "  - 快捷提示: 键入 'scpm list' 查看列表，'scpm help' 查看所有命令。" -ForegroundColor Gray
}

function Invoke-ScpmList {
    [CmdletBinding()]
    param([switch]$Detail)

    $reg = Get-ScpmRegistryInternal
    $config = Get-ScpmConfigInternal

    Write-Host "`n=== [scpm] 脚本管理清单 ===" -ForegroundColor Cyan
    if ($null -ne $config) {
        Write-Host "存储库路径: $($config.storagePath)`n" -ForegroundColor DarkGray
    }

    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。使用 'scpm add <文件路径>' 或 'scpm new <名称>' 开始添加！" -ForegroundColor Yellow
        return
    }

    $total = 0
    $enabled = 0
    $disabled = 0
    $idx = 1

    foreach ($prop in $reg.scripts.PSObject.Properties) {
        $item = $prop.Value
        $total++
        $realPath = Resolve-PortablePathInternal $item.path
        $fileExists = Test-Path -LiteralPath $realPath
        $mInfo = Get-ScpmScriptMethodsInternal $realPath

        $statusMark = if ($item.enabled) {
            $enabled++
            " [✓] "
        } else {
            $disabled++
            " [✗] "
        }
        $statusColor = if ($item.enabled) { "Green" } else { "DarkGray" }
        $idxStr = "[$idx]".PadRight(5)

        Write-Host " $idxStr" -ForegroundColor DarkGray -NoNewline
        Write-Host $statusMark -ForegroundColor $statusColor -NoNewline
        Write-Host "$($item.name.PadRight(22))" -ForegroundColor Cyan -NoNewline
        Write-Host "$($item.description)" -ForegroundColor White

        $indent = "            "
        if (-not $fileExists) {
            Write-Host "$indent[文件缺失] $realPath" -ForegroundColor Red
        } else {
            Write-Host "${indent}路径: $($item.path)" -ForegroundColor DarkGray
            if (-not [string]::IsNullOrWhiteSpace($mInfo.Summary)) {
                Write-Host "${indent}方法: " -NoNewline -ForegroundColor DarkGray
                Write-Host "$($mInfo.Summary)" -ForegroundColor Yellow
            }
        }

        if ($Detail -and $fileExists) {
            if ($mInfo.Functions.Count -gt 0) {
                foreach ($fn in $mInfo.Functions) {
                    if (-not $fn.IsNested) {
                        Write-Host "$indent  └─ $($fn.Signature)" -ForegroundColor White
                    }
                }
            }
        }

        $idx++
    }

    Write-Host "`n-----------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "总计: $total 个脚本 | 已启用: $enabled | 已禁用: $disabled" -ForegroundColor Gray
    Write-Host "提示: 运行 'sm toggle' 集中启停管理，'sm info <编号>' 查看方法详情。" -ForegroundColor DarkGray
}

function Invoke-ScpmTui {
    [CmdletBinding()]
    param()

    # 1. 检测终端是否支持交互式 TUI
    $isInteractive = $false
    try {
        if (-not [Console]::IsInputRedirected -and -not [Console]::IsOutputRedirected -and [Environment]::UserInteractive) {
            $null = $Host.UI.RawUI.CursorPosition
            $isInteractive = $true
        }
    } catch {
        $isInteractive = $false
    }

    if (-not $isInteractive) {
        Write-Host "[scpm] 检测到当前终端处于非交互或重定向环境，为您展示清单：" -ForegroundColor Yellow
        Invoke-ScpmList
        return
    }

    function Refresh-TuiDataInternal {
        $reg = Get-ScpmRegistryInternal
        $scriptProps = @()
        if ($null -ne $reg.scripts) {
            $scriptProps = @($reg.scripts.PSObject.Properties)
        }

        $items = [System.Collections.Generic.List[object]]::new()
        for ($i = 0; $i -lt $scriptProps.Count; $i++) {
            $p = $scriptProps[$i]
            $realPath = Resolve-PortablePathInternal $p.Value.path
            $mInfo = Get-ScpmScriptMethodsInternal $realPath
            $items.Add([PSCustomObject]@{
                Index = ($i + 1)
                Name = $p.Name
                Enabled = [bool]$p.Value.enabled
                Description = $p.Value.description
                Path = $p.Value.path
                RealPath = $realPath
                FileExists = (Test-Path -LiteralPath $realPath)
                MethodInfo = $mInfo
            })
        }
        return @{
            Registry = $reg
            Items = $items
        }
    }

    $data = Refresh-TuiDataInternal
    $items = $data.Items
    $reg = $data.Registry
    $config = Get-ScpmConfigInternal

    if ($items.Count -eq 0) {
        Write-Host "`n[scpm] 当前暂无受管理的脚本。使用 'sm add <路径>' 或 'sm new <名称>' 开始添加！" -ForegroundColor Yellow
        return
    }

    $cursor = 0
    $statusMsg = "欢迎进入 scpm 控制台！[↑/↓] 导航，[空格] 原地启停，[q] 退出。"
    $statusMsgColor = "Gray"

    $savedCursorVisible = $true
    try {
        $savedCursorVisible = [Console]::CursorVisible
        [Console]::CursorVisible = $false
    } catch {}

    Clear-Host
    $startPos = [System.Management.Automation.Host.Coordinates]::new(0, 0)

    try {
        while ($true) {
            if ($cursor -ge $items.Count) { $cursor = [Math]::Max(0, $items.Count - 1) }

            $currItem = $items[$cursor]
            $currMethodInfo = $currItem.MethodInfo

            $winWidth = 84
            try {
                $winWidth = [Math]::Max(70, [Math]::Min(110, $Host.UI.RawUI.WindowSize.Width - 1))
            } catch {}

            $borderLine = "─" * $winWidth

            # 重置光标到左上角重绘
            try { $Host.UI.RawUI.CursorPosition = $startPos } catch {}

            # --- 区域 1: 标题与统计 ---
            $enabledCount = @($items | Where-Object { $_.Enabled }).Count
            $disabledCount = $items.Count - $enabledCount
            $storePathStr = if ($config) { $config.storagePath } else { "$HOME\.scpm\scripts" }

            Write-Host "=== [scpm] 脚本集中管理控制台 v$Script:ScpmVersion ===".PadRight($winWidth) -ForegroundColor Cyan
            Write-Host "存储库: $storePathStr | 总计: $($items.Count) 个脚本 (已启用: $enabledCount, 已禁用: $disabledCount)".PadRight($winWidth) -ForegroundColor DarkGray
            Write-Host ""

            # --- 区域 2: 脚本列表区 ---
            Write-Host "[受管理脚本列表] (按空格键即时翻转启停状态)".PadRight($winWidth) -ForegroundColor Yellow

            for ($i = 0; $i -lt $items.Count; $i++) {
                $it = $items[$i]
                $isCurrent = ($i -eq $cursor)

                $ptr = if ($isCurrent) { " > " } else { "   " }
                $pColor = if ($isCurrent) { "Yellow" } else { "DarkGray" }
                
                $st = if ($it.Enabled) { "[✓ 已启用]" } else { "[✗ 已禁用]" }
                $stColor = if ($it.Enabled) { "Green" } else { "DarkGray" }

                $idxStr = "[$($it.Index)]".PadRight(5)
                $nameStr = $it.Name.PadRight(22)
                $descStr = $it.Description

                Write-Host $ptr -ForegroundColor $pColor -NoNewline
                Write-Host $idxStr -ForegroundColor DarkGray -NoNewline
                Write-Host " $st " -ForegroundColor $stColor -NoNewline
                Write-Host $nameStr -ForegroundColor (if ($isCurrent) { "Cyan" } else { "White" }) -NoNewline

                $usedLen = 3 + 5 + 10 + 22 + 2
                $remLen = [Math]::Max(10, $winWidth - $usedLen)
                $descPadded = if ($descStr.Length -gt $remLen) { $descStr.Substring(0, $remLen - 3) + "..." } else { $descStr.PadRight($remLen) }
                Write-Host " $descPadded" -ForegroundColor Gray
            }

            Write-Host ""
            Write-Host ("─" * [Math]::Min($winWidth, 80)) -ForegroundColor DarkCyan

            # --- 区域 3: 实时导出方法与用法联动预览区 ---
            Write-Host "[实时导出方法与用法预览: $($currItem.Name)]".PadRight($winWidth) -ForegroundColor Yellow
            Write-Host "  文件路径: $($currItem.Path)".PadRight($winWidth) -ForegroundColor DarkGray
            
            Write-Host "  导出方法 / 全局函数:".PadRight($winWidth) -ForegroundColor Green
            if ($currMethodInfo.Functions.Count -eq 0) {
                Write-Host "    • (该脚本未定义函数，作为独立脚本直接执行)".PadRight($winWidth) -ForegroundColor DarkGray
            } else {
                $shownFuncCount = 0
                foreach ($fn in $currMethodInfo.Functions) {
                    if (-not $fn.IsNested -and $shownFuncCount -lt 4) {
                        Write-Host "    • " -NoNewline -ForegroundColor Cyan
                        Write-Host "$($fn.Signature)" -ForegroundColor White
                        if ($fn.Parameters.Count -gt 0) {
                            foreach ($param in $fn.Parameters) {
                                if ($param.ValidateSet.Count -gt 0) {
                                    Write-Host "        $($param.Name) 可选值: $($param.ValidateSet -join ', ')".PadRight($winWidth) -ForegroundColor Yellow
                                }
                            }
                        }
                        $shownFuncCount++
                    }
                }
                $nested = @($currMethodInfo.Functions | Where-Object { $_.IsNested })
                if ($nested.Count -gt 0) {
                    $nestedNames = ($nested | ForEach-Object { $_.Name }) -join ", "
                    Write-Host "    (内部辅助函数: $nestedNames)".PadRight($winWidth) -ForegroundColor DarkGray
                }
            }

            if (-not [string]::IsNullOrWhiteSpace($currMethodInfo.Usage)) {
                Write-Host "  用法示例 (USAGE):".PadRight($winWidth) -ForegroundColor Green
                $uLines = $currMethodInfo.Usage -split '\r?\n'
                $shownUsage = 0
                foreach ($ul in $uLines) {
                    if (-not [string]::IsNullOrWhiteSpace($ul) -and $shownUsage -lt 4) {
                        $ulText = "    " + $ul.Trim()
                        Write-Host $ulText.PadRight($winWidth) -ForegroundColor Gray
                        $shownUsage++
                    }
                }
            } elseif (-not [string]::IsNullOrWhiteSpace($currMethodInfo.Description)) {
                Write-Host "  详细说明:".PadRight($winWidth) -ForegroundColor Green
                $dLines = $currMethodInfo.Description -split '\r?\n'
                $shownDesc = 0
                foreach ($dl in $dLines) {
                    if (-not [string]::IsNullOrWhiteSpace($dl) -and $shownDesc -lt 3) {
                        Write-Host ("    " + $dl.Trim()).PadRight($winWidth) -ForegroundColor Gray
                        $shownDesc++
                    }
                }
            }

            Write-Host ("─" * [Math]::Min($winWidth, 80)) -ForegroundColor DarkCyan

            # --- 区域 4: 底部快捷键提示与状态条 ---
            Write-Host "快捷键: [↑/↓] 移动 | [空格] 启停切换 | [e] 编辑 | [n] 新建 | [s] 同步 | [r] 移除 | [q] 退出".PadRight($winWidth) -ForegroundColor DarkGray
            Write-Host "状态提示: $statusMsg".PadRight($winWidth) -ForegroundColor $statusMsgColor

            # 清除可能残留的多余行
            for ($k = 0; $k -lt 3; $k++) {
                Write-Host (" " * $winWidth)
            }
            try { $Host.UI.RawUI.CursorPosition = [System.Management.Automation.Host.Coordinates]::new(0, $Host.UI.RawUI.CursorPosition.Y - 3) } catch {}

            # --- 键盘事件监听 ---
            $key = [Console]::ReadKey($true)
            switch ($key.Key) {
                ([ConsoleKey]::UpArrow) {
                    $cursor = ($cursor - 1 + $items.Count) % $items.Count
                }
                ([ConsoleKey]::DownArrow) {
                    $cursor = ($cursor + 1) % $items.Count
                }
                ([ConsoleKey]::Spacebar) {
                    $it = $items[$cursor]
                    $it.Enabled = -not $it.Enabled
                    $reg.scripts.PSObject.Properties[$it.Name].Value.enabled = $it.Enabled
                    Save-ScpmRegistryInternal $reg
                    Update-ScpmLoaderInternal | Out-Null

                    if ($it.Enabled) {
                        if (Test-Path -LiteralPath $it.RealPath) {
                            try {
                                . $it.RealPath
                                $statusMsg = "[✓] 已启用 $($it.Name) 并即时载入当前终端！"
                                $statusMsgColor = "Green"
                            } catch {
                                $statusMsg = "[✓] 已启用 $($it.Name) (载入告警: $($_.Exception.Message))"
                                $statusMsgColor = "Yellow"
                            }
                        }
                    } else {
                        $statusMsg = "[✗] 已禁用 $($it.Name) (新开终端将不再载入)。"
                        $statusMsgColor = "Yellow"
                    }
                }
                default {
                    $ch = [string]$key.KeyChar
                    if ($ch -in @("q", "Q") -or $key.Key -eq [ConsoleKey]::Escape) {
                        break
                    } elseif ($ch -in @("e", "E")) {
                        $it = $items[$cursor]
                        if (Test-Path -LiteralPath $it.RealPath) {
                            if (Get-Command code -ErrorAction SilentlyContinue) {
                                Start-Process "code" -ArgumentList "`"$($it.RealPath)`""
                            } else {
                                Start-Process "notepad.exe" -ArgumentList "`"$($it.RealPath)`""
                            }
                            $statusMsg = "已在编辑器中打开 $($it.Name)。"
                            $statusMsgColor = "Cyan"
                        }
                    } elseif ($ch -in @("n", "N")) {
                        try { [Console]::CursorVisible = $true } catch {}
                        Write-Host ""
                        $newName = Read-Host "请输入新脚本名称 (回车取消)"
                        if (-not [string]::IsNullOrWhiteSpace($newName)) {
                            $newDesc = Read-Host "请输入脚本描述 (可选)"
                            Invoke-ScpmNew $newName -Desc $newDesc -NoEdit
                            $data = Refresh-TuiDataInternal
                            $items = $data.Items
                            $reg = $data.Registry
                            $cursor = $items.Count - 1
                            $statusMsg = "[✓] 成功创建新脚本: $newName！"
                            $statusMsgColor = "Green"
                            Clear-Host
                        }
                        try { [Console]::CursorVisible = $false } catch {}
                    } elseif ($ch -in @("s", "S")) {
                        Invoke-ScpmSync | Out-Null
                        $data = Refresh-TuiDataInternal
                        $items = $data.Items
                        $reg = $data.Registry
                        $statusMsg = "[✓] 存储库同步扫描完成，清单已刷新。"
                        $statusMsgColor = "Green"
                        Clear-Host
                    } elseif ($ch -in @("r", "R") -or $key.Key -eq [ConsoleKey]::Delete) {
                        $it = $items[$cursor]
                        try { [Console]::CursorVisible = $true } catch {}
                        Write-Host ""
                        $confirm = Read-Host "确认从管理清单注销 $($it.Name) 吗？(y/N)"
                        if ($confirm.Trim().ToLower() -eq "y") {
                            Invoke-ScpmRemove $it.Name | Out-Null
                            $data = Refresh-TuiDataInternal
                            $items = $data.Items
                            $reg = $data.Registry
                            if ($cursor -ge $items.Count) { $cursor = [Math]::Max(0, $items.Count - 1) }
                            $statusMsg = "[✓] 已注销脚本: $($it.Name)。"
                            $statusMsgColor = "Yellow"
                            Clear-Host
                        }
                        try { [Console]::CursorVisible = $false } catch {}
                    } elseif ($ch -in @("a", "A")) {
                        foreach ($it in $items) {
                            $it.Enabled = $true
                            $reg.scripts.PSObject.Properties[$it.Name].Value.enabled = $true
                            if (Test-Path -LiteralPath $it.RealPath) {
                                try { . $it.RealPath } catch {}
                            }
                        }
                        Save-ScpmRegistryInternal $reg
                        Update-ScpmLoaderInternal | Out-Null
                        $statusMsg = "[✓] 已全部启用并即时注入当前会话！"
                        $statusMsgColor = "Green"
                    } elseif ($ch -in @("d", "D")) {
                        foreach ($it in $items) {
                            $it.Enabled = $false
                            $reg.scripts.PSObject.Properties[$it.Name].Value.enabled = $false
                        }
                        Save-ScpmRegistryInternal $reg
                        Update-ScpmLoaderInternal | Out-Null
                        $statusMsg = "[✗] 已全部禁用。"
                        $statusMsgColor = "Yellow"
                    } elseif ($ch -in @("k", "K")) {
                        $cursor = ($cursor - 1 + $items.Count) % $items.Count
                    } elseif ($ch -in @("j", "J")) {
                        $cursor = ($cursor + 1) % $items.Count
                    } elseif ($ch -in @("?", "h", "H")) {
                        $statusMsg = "[↑/↓] 移动 | [空格] 启停 | [e] 编辑 | [n] 新建 | [s] 同步 | [r] 注销 | [q] 退出"
                        $statusMsgColor = "Cyan"
                    } else {
                        $num = 0
                        if ([int]::TryParse($ch, [ref]$num) -and $num -ge 1 -and $num -le $items.Count) {
                            $cursor = $num - 1
                        }
                    }
                }
            }

            if ($key.KeyChar -in @("q", "Q") -or $key.Key -eq [ConsoleKey]::Escape) {
                break
            }
        }
    } finally {
        try { [Console]::CursorVisible = $savedCursorVisible } catch {}
        Write-Host "`n[scpm] 已退出控制台。" -ForegroundColor Gray
    }
}

function Invoke-ScpmToggle {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
        [string[]]$Targets
    )

    $cleanTargets = @()
    if ($null -ne $Targets) {
        $cleanTargets = @($Targets | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    }

    if ($cleanTargets.Count -gt 0) {
        $reg = Get-ScpmRegistryInternal
        if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
            Write-Host "当前暂无受管理的脚本。使用 'scpm add <路径>' 添加脚本。" -ForegroundColor Yellow
            return
        }
        $scriptProps = @($reg.scripts.PSObject.Properties)
        $updated = $false
        foreach ($t in $cleanTargets) {
            $matchedProps = Resolve-ScpmScriptPropsInternal $t $scriptProps
            if ($matchedProps.Count -eq 0) {
                Write-Host "[错误] 未找到匹配 '$t' 的脚本。" -ForegroundColor Red
                continue
            }
            foreach ($prop in $matchedProps) {
                $item = $prop.Value
                $item.enabled = -not $item.enabled
                $updated = $true
                if ($item.enabled) {
                    Write-Host "[✓] 已启用: $($prop.Name)" -ForegroundColor Green
                    $realPath = Resolve-PortablePathInternal $item.path
                    if (Test-Path -LiteralPath $realPath) {
                        try {
                            . $realPath
                            Write-Host "    已即时载入当前终端会话。" -ForegroundColor Gray
                        } catch {
                            Write-Warning "    即时载入失败: $($_.Exception.Message)"
                        }
                    }
                } else {
                    Write-Host "[✗] 已禁用: $($prop.Name) (将在新终端会话生效)" -ForegroundColor Yellow
                }
            }
        }
        if ($updated) {
            Save-ScpmRegistryInternal $reg
            Update-ScpmLoaderInternal | Out-Null
        }
    } else {
        Invoke-ScpmTui
    }
}

function Invoke-ScpmEnable {
    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。使用 'scpm add <路径>' 添加脚本。" -ForegroundColor Yellow
        return
    }

    if ($args.Count -eq 0) {
        Invoke-ScpmToggle
        return
    }

    $scriptProps = @($reg.scripts.PSObject.Properties)
    $updated = $false

    foreach ($rawName in $args) {
        $matchedProps = Resolve-ScpmScriptPropsInternal $rawName $scriptProps
        if ($matchedProps.Count -eq 0) {
            Write-Host "[错误] 未找到名为或序号为 '$rawName' 的脚本。" -ForegroundColor Red
            continue
        }

        foreach ($prop in $matchedProps) {
            $item = $prop.Value
            if (-not $item.enabled) {
                $item.enabled = $true
                $updated = $true
                Write-Host "[✓] 已启用: $($prop.Name)" -ForegroundColor Green
                
                $realPath = Resolve-PortablePathInternal $item.path
                if (Test-Path -LiteralPath $realPath) {
                    try {
                        . $realPath
                        $mInfo = Get-ScpmScriptMethodsInternal $realPath
                        $m = if ($mInfo.Summary) { " (导出方法: $($mInfo.Summary))" } else { "" }
                        Write-Host "    已即时载入当前终端会话$m。" -ForegroundColor Gray
                    } catch {
                        Write-Warning "    即时载入失败: $($_.Exception.Message)"
                    }
                }
            } else {
                Write-Host "[提示] $($prop.Name) 已经是启用状态。" -ForegroundColor Yellow
            }
        }
    }

    if ($updated) {
        Save-ScpmRegistryInternal $reg
        Update-ScpmLoaderInternal | Out-Null
    }
}

function Invoke-ScpmDisable {
    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。" -ForegroundColor Yellow
        return
    }

    if ($args.Count -eq 0) {
        Invoke-ScpmToggle
        return
    }

    $scriptProps = @($reg.scripts.PSObject.Properties)
    $updated = $false

    foreach ($rawName in $args) {
        $matchedProps = Resolve-ScpmScriptPropsInternal $rawName $scriptProps
        if ($matchedProps.Count -eq 0) {
            Write-Host "[错误] 未找到名为或序号为 '$rawName' 的脚本。" -ForegroundColor Red
            continue
        }

        foreach ($prop in $matchedProps) {
            $item = $prop.Value
            if ($item.enabled) {
                $item.enabled = $false
                $updated = $true
                Write-Host "[✗] 已禁用: $($prop.Name) (将在下次新开会话生效)" -ForegroundColor Yellow
            } else {
                Write-Host "[提示] $($prop.Name) 已经是禁用状态。" -ForegroundColor Gray
            }
        }
    }

    if ($updated) {
        Save-ScpmRegistryInternal $reg
        Update-ScpmLoaderInternal | Out-Null
    }
}

function Show-SingleScriptInfoInternal([int]$index, [string]$name, [object]$item) {
    $realPath = Resolve-PortablePathInternal $item.path
    $mInfo = Get-ScpmScriptMethodsInternal $realPath

    Write-Host ""
    Write-Host "================================================================================" -ForegroundColor Cyan
    Write-Host " [$index] 脚本: " -NoNewline -ForegroundColor Cyan
    Write-Host "$name" -ForegroundColor Yellow -NoNewline
    if ($item.enabled) {
        Write-Host "  [✓ 已启用 - 自动注入当前终端]" -ForegroundColor Green
    } else {
        Write-Host "  [✗ 已禁用]" -ForegroundColor DarkGray
    }
    Write-Host "================================================================================" -ForegroundColor Cyan

    Write-Host "  文件路径: " -NoNewline -ForegroundColor DarkGray
    if ($mInfo.FileExists) {
        Write-Host "$($item.path)" -ForegroundColor White
    } else {
        Write-Host "$($item.path) [文件缺失!]" -ForegroundColor Red
        return
    }

    if (-not [string]::IsNullOrWhiteSpace($item.description)) {
        Write-Host "  脚本简介: " -NoNewline -ForegroundColor DarkGray
        Write-Host "$($item.description)" -ForegroundColor Gray
    }

    Write-Host "`n  [提供的方法 / 导出函数]" -ForegroundColor Green
    if ($mInfo.Functions.Count -eq 0) {
        Write-Host "    • (该脚本未定义函数，作为脚本文件直接执行)" -ForegroundColor DarkGray
    } else {
        foreach ($fn in $mInfo.Functions) {
            if (-not $fn.IsNested) {
                Write-Host "    • " -NoNewline -ForegroundColor Cyan
                Write-Host "$($fn.Signature)" -ForegroundColor White
                if ($fn.Parameters.Count -gt 0) {
                    foreach ($param in $fn.Parameters) {
                        if ($param.ValidateSet.Count -gt 0) {
                            Write-Host "        $($param.Name) 可选值: " -NoNewline -ForegroundColor DarkGray
                            Write-Host "$($param.ValidateSet -join ', ')" -ForegroundColor Yellow
                        }
                    }
                }
            }
        }
        $nestedFuncs = @($mInfo.Functions | Where-Object { $_.IsNested })
        if ($nestedFuncs.Count -gt 0) {
            $nestedNames = ($nestedFuncs | ForEach-Object { $_.Name }) -join ", "
            Write-Host "    (内部辅助函数: $nestedNames)" -ForegroundColor DarkGray
        }
    }

    if ($mInfo.Aliases.Count -gt 0) {
        Write-Host "`n  [导出的别名 (Aliases)]" -ForegroundColor Green
        foreach ($al in $mInfo.Aliases) {
            Write-Host "    • $($al.Name) -> $($al.Target)" -ForegroundColor Cyan
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($mInfo.Usage)) {
        Write-Host "`n  [用法示例 (USAGE)]" -ForegroundColor Green
        $uLines = $mInfo.Usage -split '\r?\n'
        foreach ($ul in $uLines) {
            Write-Host "    $ul" -ForegroundColor Gray
        }
    } elseif (-not [string]::IsNullOrWhiteSpace($mInfo.Description)) {
        Write-Host "`n  [详细说明 (DESCRIPTION)]" -ForegroundColor Green
        $dLines = $mInfo.Description -split '\r?\n'
        foreach ($dl in $dLines) {
            Write-Host "    $dl" -ForegroundColor Gray
        }
    }

    Write-Host ""
}

function Invoke-ScpmInfo {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
        [string[]]$Targets,

        [switch]$All
    )

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。使用 'scpm add <路径>' 添加脚本。" -ForegroundColor Yellow
        return
    }

    $scriptProps = @($reg.scripts.PSObject.Properties)

    # 1. 检查是否查看全部
    $showAll = $All.IsPresent -or ($Targets -contains "-All") -or ($Targets -contains "--all") -or ($Targets -contains "-a") -or ($Targets -contains "all")

    if ($showAll) {
        Write-Host "`n=== [scpm] 全部受管理脚本方法与函数总览 ===" -ForegroundColor Cyan
        for ($i = 0; $i -lt $scriptProps.Count; $i++) {
            $p = $scriptProps[$i]
            Show-SingleScriptInfoInternal ($i + 1) $p.Name $p.Value
        }
        return
    }

    # 2. 如果没有传参，进行交互式选择
    if ($null -eq $Targets -or $Targets.Count -eq 0) {
        Write-Host "`n=== [scpm] 脚本方法与命令详情查询 ===" -ForegroundColor Cyan
        for ($i = 0; $i -lt $scriptProps.Count; $i++) {
            $p = $scriptProps[$i]
            $st = if ($p.Value.enabled) { "[✓]" } else { "[✗]" }
            $stColor = if ($p.Value.enabled) { "Green" } else { "DarkGray" }
            Write-Host "  [$($i + 1)] " -NoNewline -ForegroundColor White
            Write-Host "$st " -NoNewline -ForegroundColor $stColor
            Write-Host "$($p.Name.PadRight(22))" -NoNewline -ForegroundColor Cyan
            Write-Host "$($p.Value.description)" -ForegroundColor Gray
        }
        Write-Host "  [a] 查看所有脚本提供的方法清单" -ForegroundColor Yellow

        $choice = Read-Host "`n请选择要查看的脚本编号 [1-$($scriptProps.Count)] (输入 a 查看全部, q 退出)"
        if ([string]::IsNullOrWhiteSpace($choice) -or $choice.Trim().ToLower() -in @("q", "quit", "exit")) {
            return
        }
        if ($choice.Trim().ToLower() -in @("a", "all")) {
            Invoke-ScpmInfo -All
            return
        }
        $Targets = @($choice.Trim())
    }

    # 3. 显示指定的脚本详情
    foreach ($t in $Targets) {
        $matchedProps = Resolve-ScpmScriptPropsInternal $t $scriptProps
        if ($matchedProps.Count -eq 0) {
            Write-Host "[错误] 未找到匹配 '$t' 的脚本。" -ForegroundColor Red
            continue
        }
        foreach ($prop in $matchedProps) {
            $idx = ($scriptProps.IndexOf($prop) + 1)
            Show-SingleScriptInfoInternal $idx $prop.Name $prop.Value
        }
    }
}

function Invoke-ScpmAdd {
    $Path = ""
    $Name = ""
    $Desc = ""
    $NoCopy = $false
    $Disable = $false

    for ($i = 0; $i -lt $args.Count; $i++) {
        $curr = $args[$i]
        if ($curr -in @("-Name", "-n", "--name") -and ($i + 1 -lt $args.Count)) {
            $Name = $args[++$i]
        } elseif ($curr -in @("-Desc", "-d", "--desc") -and ($i + 1 -lt $args.Count)) {
            $Desc = $args[++$i]
        } elseif ($curr -in @("-NoCopy", "--no-copy")) {
            $NoCopy = $true
        } elseif ($curr -in @("-Disable", "--disable")) {
            $Disable = $true
        } elseif (-not $Path) {
            $Path = $curr
        }
    }

    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Host "[错误] 指定的文件不存在: $Path" -ForegroundColor Red
        return
    }

    $config = Get-ScpmConfigInternal
    if ($null -eq $config) {
        Write-Host "[错误] scpm 尚未初始化，请先运行 'scpm init'。" -ForegroundColor Red
        return
    }

    $sourceItem = Get-Item -LiteralPath $Path
    $targetName = if (-not [string]::IsNullOrWhiteSpace($Name)) {
        if ($Name.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $Name } else { "$Name.ps1" }
    } else {
        $sourceItem.Name
    }

    $storageDir = Resolve-PortablePathInternal $config.storagePath
    $destPath = Join-Path $storageDir $targetName

    if ((-not $NoCopy) -and ($sourceItem.FullName -ne $destPath)) {
        Copy-Item -LiteralPath $sourceItem.FullName -Destination $destPath -Force
        Write-Host "[文件] 已拷贝到脚本仓库: $destPath" -ForegroundColor Gray
        $finalPath = $destPath
    } else {
        $finalPath = $sourceItem.FullName
    }

    if ([string]::IsNullOrWhiteSpace($Desc)) {
        $Desc = Extract-ScriptSynopsisInternal $finalPath
        if ([string]::IsNullOrWhiteSpace($Desc)) {
            $Desc = "自定义脚本: $targetName"
        }
    }

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    $reg.scripts | Add-Member -NotePropertyName $targetName -NotePropertyValue ([PSCustomObject]@{
        name = $targetName
        enabled = (-not $Disable)
        description = $Desc
        path = ConvertTo-PortablePath $finalPath
        addedAt = (Get-Date -Format "o")
    }) -Force

    Save-ScpmRegistryInternal $reg
    Update-ScpmLoaderInternal | Out-Null

    $statusStr = if (-not $Disable) { "并已启用注入" } else { "处于禁用状态" }
    Write-Host "[成功] 脚本 '$targetName' 已添加成功 ($statusStr)！" -ForegroundColor Green
}

function Invoke-ScpmNew {
    $Name = ""
    $Desc = ""
    $NoEdit = $false

    for ($i = 0; $i -lt $args.Count; $i++) {
        $curr = $args[$i]
        if ($curr -in @("-Desc", "-d", "--desc") -and ($i + 1 -lt $args.Count)) {
            $Desc = $args[++$i]
        } elseif ($curr -in @("-NoEdit", "-n", "--no-edit")) {
            $NoEdit = $true
        } elseif (-not $Name) {
            $Name = $curr
        }
    }

    $config = Get-ScpmConfigInternal
    if ($null -eq $config) {
        Write-Host "[错误] scpm 尚未初始化，请先运行 'scpm init'。" -ForegroundColor Red
        return
    }

    $targetName = if ($Name.EndsWith(".ps1", [System.StringComparison]::OrdinalIgnoreCase)) { $Name } else { "$Name.ps1" }
    $storageDir = Resolve-PortablePathInternal $config.storagePath
    $targetFile = Join-Path $storageDir $targetName

    if (Test-Path -LiteralPath $targetFile) {
        Write-Host "[错误] 脚本 '$targetName' 已存在于存储目录中。" -ForegroundColor Red
        return
    }

    if ([string]::IsNullOrWhiteSpace($Desc)) {
        $Desc = "PowerShell 脚本 $targetName"
    }

    $fnName = [System.IO.Path]::GetFileNameWithoutExtension($targetName)

    $template = @"
<#
.SYNOPSIS
    $Desc
.DESCRIPTION
    由 scpm (PowerShell Script Profile Manager) 创建
#>

function $fnName {
    [CmdletBinding()]
    param()
    
    Write-Host "[$fnName] 脚本正在运行..." -ForegroundColor Green
}
"@

    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($targetFile, $template, $utf8Bom)

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    $reg.scripts | Add-Member -NotePropertyName $targetName -NotePropertyValue ([PSCustomObject]@{
        name = $targetName
        enabled = $true
        description = $Desc
        path = ConvertTo-PortablePath $targetFile
        addedAt = (Get-Date -Format "o")
    }) -Force

    Save-ScpmRegistryInternal $reg
    Update-ScpmLoaderInternal | Out-Null

    Write-Host "[成功] 已创建新脚本: $targetName (默认启用)" -ForegroundColor Green

    if (-not $NoEdit) {
        Invoke-ScpmEdit $targetName
    }
}

function Invoke-ScpmEdit {
    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。" -ForegroundColor Yellow
        return
    }

    $scriptProps = @($reg.scripts.PSObject.Properties)
    $targetProp = $null

    if ($args.Count -eq 0) {
        $targetProp = Select-ScpmScriptSingleInteractive "请选择要编辑的脚本" $scriptProps
        if ($null -eq $targetProp) { return }
    } else {
        $matchedProps = Resolve-ScpmScriptPropsInternal $args[0] $scriptProps
        if ($matchedProps.Count -eq 0) {
            Write-Host "[错误] 未找到脚本: $($args[0])" -ForegroundColor Red
            return
        }
        $targetProp = $matchedProps[0]
    }

    $realPath = Resolve-PortablePathInternal $targetProp.Value.path
    if (-not (Test-Path -LiteralPath $realPath)) {
        Write-Host "[错误] 脚本文件不存在: $realPath" -ForegroundColor Red
        return
    }

    if (Get-Command code -ErrorAction SilentlyContinue) {
        Start-Process "code" -ArgumentList "`"$realPath`""
    } else {
        Start-Process "notepad.exe" -ArgumentList "`"$realPath`""
    }
    Write-Host "[编辑] 已用编辑器打开: $realPath" -ForegroundColor Gray
}

function Invoke-ScpmRemove {
    $Name = ""
    $DeleteFile = $false

    foreach ($curr in $args) {
        if ($curr -in @("-DeleteFile", "-Delete", "-d", "--delete")) {
            $DeleteFile = $true
        } elseif (-not $Name) {
            $Name = $curr
        }
    }

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts -or $reg.scripts.PSObject.Properties.Count -eq 0) {
        Write-Host "当前暂无受管理的脚本。" -ForegroundColor Yellow
        return
    }

    $scriptProps = @($reg.scripts.PSObject.Properties)
    $targetProp = $null

    if ([string]::IsNullOrWhiteSpace($Name)) {
        $targetProp = Select-ScpmScriptSingleInteractive "请选择要从清单移除的脚本" $scriptProps
        if ($null -eq $targetProp) { return }
    } else {
        $matchedProps = Resolve-ScpmScriptPropsInternal $Name $scriptProps
        if ($matchedProps.Count -eq 0) {
            Write-Host "[错误] 未在管理列表中找到: $Name" -ForegroundColor Red
            return
        }
        $targetProp = $matchedProps[0]
    }

    $toRemove = $targetProp.Name
    $filePath = Resolve-PortablePathInternal $targetProp.Value.path

    $reg.scripts.PSObject.Properties.Remove($toRemove)
    Save-ScpmRegistryInternal $reg
    Update-ScpmLoaderInternal | Out-Null
    Write-Host "[✓] 已从管理清单注销: $toRemove" -ForegroundColor Green

    if ($DeleteFile -and (Test-Path -LiteralPath $filePath)) {
        Remove-Item -LiteralPath $filePath -Force
        Write-Host "    [已删除物理文件] $filePath" -ForegroundColor Yellow
    }
}

function Invoke-ScpmSync {
    [CmdletBinding()]
    param()

    $config = Get-ScpmConfigInternal
    if ($null -eq $config) {
        Write-Host "[错误] scpm 尚未初始化。" -ForegroundColor Red
        return
    }

    $storageDir = Resolve-PortablePathInternal $config.storagePath
    if (-not (Test-Path -LiteralPath $storageDir)) {
        Write-Host "[错误] 存储目录不存在: $storageDir" -ForegroundColor Red
        return
    }

    $reg = Get-ScpmRegistryInternal
    if ($null -eq $reg.scripts) {
        $reg | Add-Member -NotePropertyName "scripts" -NotePropertyValue ([PSCustomObject]@{}) -Force
    }

    Write-Host "`n=== [scpm] 正在同步存储库 ===`n" -ForegroundColor Cyan
    $files = Get-ChildItem -LiteralPath $storageDir -Filter "*.ps1" -File

    $added = 0
    foreach ($f in $files) {
        if (-not $reg.scripts.PSObject.Properties[$f.Name]) {
            $desc = Extract-ScriptSynopsisInternal $f.FullName
            if ([string]::IsNullOrWhiteSpace($desc)) { $desc = "自定义脚本: $($f.Name)" }
            $pPath = ConvertTo-PortablePath $f.FullName

            $reg.scripts | Add-Member -NotePropertyName $f.Name -NotePropertyValue ([PSCustomObject]@{
                name = $f.Name
                enabled = $true
                description = $desc
                path = $pPath
                addedAt = (Get-Date -Format "o")
            }) -Force
            Write-Host "  [发现新脚本] 已添加并启用: $($f.Name) ($desc)" -ForegroundColor Green
            $added++
        }
    }

    # 检查缺失
    $missing = 0
    foreach ($prop in $reg.scripts.PSObject.Properties) {
        $p = Resolve-PortablePathInternal $prop.Value.path
        if (-not (Test-Path -LiteralPath $p)) {
            Write-Host "  [警告] 脚本文件缺失: $($prop.Name) ($p)" -ForegroundColor Yellow
            $missing++
        }
    }

    Save-ScpmRegistryInternal $reg
    $enabled = Update-ScpmLoaderInternal
    Write-Host "`n同步完毕: 新增 $added 个脚本，文件缺失 $missing 个，当前共启用 $enabled 个。" -ForegroundColor Gray
}

function Invoke-ScpmDoctor {
    [CmdletBinding()]
    param()

    Write-Host "`n=== [scpm] 环境健康检查与体检报告 ===" -ForegroundColor Cyan
    
    # 1. 核心目录与配置
    Write-Host "`n[1/4] 配置与元数据状态" -ForegroundColor Green
    if (Test-Path -LiteralPath $Script:ConfigFile) {
        Write-Host "  [✓] 配置文件正常: $Script:ConfigFile" -ForegroundColor Green
    } else {
        Write-Host "  [✗] 配置文件不存在 (请运行 scpm init)" -ForegroundColor Red
    }

    if (Test-Path -LiteralPath $Script:RegistryFile) {
        Write-Host "  [✓] 注册表文件正常: $Script:RegistryFile" -ForegroundColor Green
    } else {
        Write-Host "  [✗] 注册表文件不存在" -ForegroundColor Red
    }

    # 2. 存储库可达性
    Write-Host "`n[2/4] 存储库可达性与坚果云同步" -ForegroundColor Green
    $config = Get-ScpmConfigInternal
    if ($null -ne $config) {
        $realStorage = Resolve-PortablePathInternal $config.storagePath
        if (Test-Path -LiteralPath $realStorage) {
            $isNutstore = $realStorage -like "*Nutstore*" -or $realStorage -like "*坚果云*"
            $tag = if ($isNutstore) { "[坚果云云同步]" } else { "[本地目录]" }
            Write-Host "  [✓] 存储库路径正常 ${tag}: $realStorage" -ForegroundColor Green
        } else {
            Write-Host "  [✗] 存储库路径无法访问: $realStorage" -ForegroundColor Red
        }
    } else {
        Write-Host "  [!] 暂无配置信息" -ForegroundColor Yellow
    }

    # 3. Profile 钩子状态
    Write-Host "`n[3/4] PowerShell Profile 注入检查" -ForegroundColor Green
    $profiles = @(
        @{ Name = "PowerShell 7"; Path = (Join-Path $HOME "Documents\PowerShell\Microsoft.PowerShell_profile.ps1") },
        @{ Name = "Windows PowerShell 5.1"; Path = (Join-Path $HOME "Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1") }
    )

    foreach ($pf in $profiles) {
        if (Test-Path -LiteralPath $pf.Path) {
            $content = [System.IO.File]::ReadAllText($pf.Path, [System.Text.Encoding]::UTF8)
            if ($content -match 'scpm loader start') {
                Write-Host "  [✓] $($pf.Name): 已挂载 scpm loader" -ForegroundColor Green
            } else {
                Write-Host "  [!] $($pf.Name): 尚未注入 loader 钩子 (可执行 scpm init 自动挂载)" -ForegroundColor Yellow
            }
        } else {
            Write-Host "  [!] $($pf.Name): Profile 文件不存在" -ForegroundColor DarkGray
        }
    }

    # 4. 脚本完整度
    Write-Host "`n[4/4] 脚本健康度检查" -ForegroundColor Green
    $reg = Get-ScpmRegistryInternal
    $valid = 0
    $broken = 0
    foreach ($prop in $reg.scripts.PSObject.Properties) {
        $real = Resolve-PortablePathInternal $prop.Value.path
        if (Test-Path -LiteralPath $real) {
            $valid++
        } else {
            $broken++
            Write-Host "  [✗] 缺失文件: $($prop.Name) -> $real" -ForegroundColor Red
        }
    }
    if ($broken -eq 0) {
        Write-Host "  [✓] 所有已登记脚本文件完整 ($valid/$valid)" -ForegroundColor Green
    }

    Write-Host "`n检查完成！" -ForegroundColor Cyan
}

function Invoke-ScpmUpdate {
    $Force = $false
    foreach ($curr in $args) {
        if ($curr -in @("-Force", "-f", "--force")) {
            $Force = $true
        }
    }

    Write-Host "`n=== [scpm] 正在检查更新... ===" -ForegroundColor Cyan
    $repoBase = "https://raw.githubusercontent.com/hbhszy/scpm/main/src"
    $psd1Url = "$repoBase/scpm.psd1"
    $psm1Url = "$repoBase/scpm.psm1"

    try {
        Write-Host "正在连接 GitHub 检查最新版本..." -ForegroundColor Gray
        $wc = New-Object System.Net.WebClient
        $wc.Encoding = [System.Text.Encoding]::UTF8
        
        $cacheBuster = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
        $remotePsd1 = $wc.DownloadString("$psd1Url?t=$cacheBuster")
        $remoteVer = "1.0.1"
        if ($remotePsd1 -match "ModuleVersion\s*=\s*['""]([^'""]+)['""]") {
            $remoteVer = $matches[1]
        }

        Write-Host "当前版本: v$Script:ScpmVersion | 远程版本: v$remoteVer" -ForegroundColor White
        
        if ($remoteVer -le $Script:ScpmVersion -and (-not $Force)) {
            Write-Host "[✓] 当前已经是最新版本 (v$Script:ScpmVersion)。如需强制重装可运行: sm update -Force" -ForegroundColor Green
            return
        }

        Write-Host "正在下载更新组件..." -ForegroundColor Yellow
        $remotePsm1 = $wc.DownloadString("$psm1Url?t=$cacheBuster")

        $utf8Bom = New-Object System.Text.UTF8Encoding($true)
        $targets = @(
            (Join-Path $HOME ".scpm"),
            (Join-Path $HOME "Documents\PowerShell\Modules\scpm"),
            (Join-Path $HOME "Documents\WindowsPowerShell\Modules\scpm")
        )

        foreach ($dir in $targets) {
            if (-not (Test-Path -LiteralPath $dir)) {
                New-Item -ItemType Directory -Path $dir -Force | Out-Null
            }
            [System.IO.File]::WriteAllText((Join-Path $dir "scpm.psm1"), $remotePsm1, $utf8Bom)
            [System.IO.File]::WriteAllText((Join-Path $dir "scpm.psd1"), $remotePsd1, $utf8Bom)
        }

        Update-ScpmLoaderInternal | Out-Null
        Import-Module (Join-Path $HOME ".scpm\scpm.psm1") -Force -DisableNameChecking -ErrorAction SilentlyContinue

        Write-Host "[✓] scpm 成功更新至 v$remoteVer！已即时载入当前会话。" -ForegroundColor Green
    } catch {
        Write-Host "[scpm] 更新检查失败: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "提示: 也可通过一键安装脚本进行重装/升级:" -ForegroundColor Yellow
        Write-Host "  irm https://raw.githubusercontent.com/hbhszy/scpm/main/install.ps1 | iex" -ForegroundColor White
    }
}

# --------------------------------------------------------------------
# 主入口命令: scpm (别名 sm)
# --------------------------------------------------------------------

function Invoke-ScpmHelp {
    [CmdletBinding()]
    param([string]$Topic = "")

    switch ($Topic) {
        { $_ -in @("on", "enable") } {
            Write-Host "`n用法: sm on [脚本名称/序号...]" -ForegroundColor Cyan
            Write-Host "说明: 启用指定脚本的自启注入，并在当前终端会话立即生效。" -ForegroundColor White
            Write-Host "示例:" -ForegroundColor Gray
            Write-Host "  sm on               # 启动集中启停管理面板 (按空格键切换)" -ForegroundColor White
            Write-Host "  sm on pxy           # 启用 pxy.ps1" -ForegroundColor White
            Write-Host "  sm on 1 2           # 批量启用序号 1 和 2 的脚本" -ForegroundColor White
            Write-Host "  sm on *             # 启用所有脚本" -ForegroundColor White
            return
        }
        { $_ -in @("off", "disable") } {
            Write-Host "`n用法: sm off [脚本名称/序号...]" -ForegroundColor Cyan
            Write-Host "说明: 禁用指定脚本的自启注入 (新开终端将不再载入)。" -ForegroundColor White
            Write-Host "示例:" -ForegroundColor Gray
            Write-Host "  sm off              # 启动集中启停管理面板 (按空格键切换)" -ForegroundColor White
            Write-Host "  sm off pxy          # 禁用 pxy.ps1" -ForegroundColor White
            Write-Host "  sm off 2            # 禁用序号 2 的脚本" -ForegroundColor White
            return
        }
        { $_ -in @("toggle", "switch", "manage", "t") } {
            Write-Host "`n用法: sm toggle [脚本名称/序号...]" -ForegroundColor Cyan
            Write-Host "说明: 集中管理脚本启停状态，或一键翻转目标脚本的启停。" -ForegroundColor White
            Write-Host "示例:" -ForegroundColor Gray
            Write-Host "  sm toggle           # 打开集中管理面板 (↑/↓ 移动光标，空格翻转启停，回车保存生效)" -ForegroundColor White
            Write-Host "  sm toggle pxy       # 翻转 pxy.ps1 的启停状态" -ForegroundColor White
            Write-Host "  sm toggle 1         # 翻转序号 1 脚本的启停状态" -ForegroundColor White
            return
        }
        { $_ -in @("info", "show", "methods", "inspect", "detail") } {
            Write-Host "`n用法: sm info [脚本名称/序号] [-All]" -ForegroundColor Cyan
            Write-Host "说明: 查看脚本提供的具体方法、函数签名、参数选项及用法示例。" -ForegroundColor White
            Write-Host "示例:" -ForegroundColor Gray
            Write-Host "  sm info             # 交互式选择要查看方法的脚本" -ForegroundColor White
            Write-Host "  sm info pxy         # 查看 pxy.ps1 导出的函数与用法" -ForegroundColor White
            Write-Host "  sm info 1           # 查看序号 1 脚本的具体方法" -ForegroundColor White
            Write-Host "  sm info -All        # 查看所有脚本提供的方法总览" -ForegroundColor White
            return
        }
        { $_ -in @("list", "ls") } {
            Write-Host "`n用法: sm list [-Detail]" -ForegroundColor Cyan
            Write-Host "说明: 列出所有受管理的脚本、序号、启停状态、存储路径及提供的方法。" -ForegroundColor White
            Write-Host "选项:" -ForegroundColor Gray
            Write-Host "  -Detail, -d         # 显示完整的函数参数签名" -ForegroundColor White
            return
        }
        default {
            Write-Host "`n=== scpm (PowerShell Script Profile Manager) v$Script:ScpmVersion ===" -ForegroundColor Cyan
            Write-Host "轻量、零依赖的 PowerShell 脚本与云同步管理器`n" -ForegroundColor White
            Write-Host "常用命令 (别名: sm):" -ForegroundColor Green
            Write-Host "  sm / sm ui / sm tui      # 打开全键盘交互式 TUI 管理控制台 (双区实时联动预览)" -ForegroundColor Yellow
            Write-Host "  sm list / ls [-d]        # 查看受管理脚本清单及导出方法 (加 -d 查看函数签名)" -ForegroundColor White
            Write-Host "  sm toggle / t [名称/序号]# 集中启停管理面板 (无参唤起，空格键交互翻转)" -ForegroundColor Yellow
            Write-Host "  sm on [名称/序号]        # 启用脚本注入 (当前会话即时生效，无参唤起控制台)" -ForegroundColor White
            Write-Host "  sm off [名称/序号]       # 禁用脚本注入 (无参唤起控制台)" -ForegroundColor White
            Write-Host "  sm info [名称/序号]      # 查看脚本具体导出的函数、参数及用法示例" -ForegroundColor Cyan
            Write-Host "  sm edit [名称/序号]      # 在编辑器中打开脚本 (无参交互选择)" -ForegroundColor White
            Write-Host "  sm new <名称>            # 快速创建新脚本脚手架模板并打开" -ForegroundColor White
            Write-Host "  sm add <路径>            # 收录现有本地脚本到存储库" -ForegroundColor White
            Write-Host "  sm rm [名称/序号]        # 从管理清单移除脚本 (追加 -DeleteFile 删除物理文件)" -ForegroundColor White
            Write-Host "  sm sync / refresh        # 同步存储库目录（如坚果云中新同步的文件）" -ForegroundColor White
            Write-Host "  sm doctor / status       # 环境健康检查 (配置、路径、Profile 挂载)" -ForegroundColor White
            Write-Host "  sm update / upgrade      # 从 GitHub 检查并一键更新 scpm" -ForegroundColor White
            Write-Host "  sm -h / help [命令]      # 查看帮助说明 (或特定子命令帮助)" -ForegroundColor White
            Write-Host "  sm -v / version          # 查看 scpm 当前版本" -ForegroundColor White
            Write-Host "`n💡 交互式 TUI 快捷提示:" -ForegroundColor DarkGray
            Write-Host "  • 直接运行 'sm' 或 'sm ui' 即可进入 TUI 控制台！" -ForegroundColor DarkGray
            Write-Host "  • [↑/↓] 移动聚焦，下半区实时刷新该脚本导出的方法与文档" -ForegroundColor DarkGray
            Write-Host "  • [空格] 原地秒切启用/禁用，[e] 打开编辑，[n] 新建，[s] 同步，[q] 退出" -ForegroundColor DarkGray
            Write-Host ""
        }
    }
}

function scpm {
    [CmdletBinding(DefaultParameterSetName = "Default")]
    param(
        [Parameter(Position = 0)]
        [string]$Subcommand,

        [Parameter(Position = 1, ValueFromRemainingArguments = $true)]
        [string[]]$RemainingArgs,

        [Alias("h", "?")]
        [switch]$Help,

        [Alias("v")]
        [switch]$Version,

        [Alias("d")]
        [switch]$Detail
    )

    $isHelp = $Help.IsPresent -or ($Subcommand -in @("help", "-h", "--help", "-?")) -or ($RemainingArgs -contains "-h") -or ($RemainingArgs -contains "--help")
    $isVersion = $Version.IsPresent -or ($Subcommand -in @("version", "-v", "--version")) -or ($RemainingArgs -contains "-v") -or ($RemainingArgs -contains "--version")

    if ($isVersion) {
        Write-Host "scpm version v$Script:ScpmVersion" -ForegroundColor Cyan
        return
    }

    if ($isHelp) {
        $topic = ""
        if ($Subcommand -notin @("help", "-h", "--help", "-?", "")) {
            $topic = $Subcommand
        } elseif ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
            $topic = $RemainingArgs[0]
        }
        Invoke-ScpmHelp $topic
        return
    }

    switch ($Subcommand) {
        "init" {
            Invoke-ScpmInit @RemainingArgs
        }
        { $_ -in @("ui", "tui") } {
            Invoke-ScpmTui
        }
        { $_ -in @("list", "ls") } {
            Invoke-ScpmList -Detail:$Detail
        }
        "" {
            if ($Detail.IsPresent) {
                Invoke-ScpmList -Detail:$true
            } else {
                $isInteractive = $false
                try {
                    if (-not [Console]::IsInputRedirected -and -not [Console]::IsOutputRedirected -and [Environment]::UserInteractive) {
                        $null = $Host.UI.RawUI.CursorPosition
                        $isInteractive = $true
                    }
                } catch { $isInteractive = $false }

                if ($isInteractive) {
                    Invoke-ScpmTui
                } else {
                    Invoke-ScpmList
                }
            }
        }
        { $_ -in @("toggle", "switch", "manage", "t") } {
            if ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
                Invoke-ScpmToggle @RemainingArgs
            } else {
                Invoke-ScpmTui
            }
        }
        { $_ -in @("enable", "on") } {
            if ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
                Invoke-ScpmEnable @RemainingArgs
            } else {
                Invoke-ScpmTui
            }
        }
        { $_ -in @("disable", "off") } {
            if ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
                Invoke-ScpmDisable @RemainingArgs
            } else {
                Invoke-ScpmTui
            }
        }
        { $_ -in @("info", "show", "methods", "inspect", "detail") } {
            if ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
                Invoke-ScpmInfo @RemainingArgs
            } else {
                Invoke-ScpmInfo
            }
        }
        "add" {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm add <脚本路径> [-Name <名称>] [-Desc <描述>]" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmAdd @RemainingArgs
        }
        "new" {
            if ($null -eq $RemainingArgs -or $RemainingArgs.Count -eq 0) {
                Write-Host "用法: scpm new <脚本名称> [-Desc <描述>]" -ForegroundColor Yellow
                return
            }
            Invoke-ScpmNew @RemainingArgs
        }
        "edit" {
            if ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
                Invoke-ScpmEdit @RemainingArgs
            } else {
                Invoke-ScpmEdit
            }
        }
        { $_ -in @("remove", "rm") } {
            if ($null -ne $RemainingArgs -and $RemainingArgs.Count -gt 0) {
                Invoke-ScpmRemove @RemainingArgs
            } else {
                Invoke-ScpmRemove
            }
        }
        { $_ -in @("sync", "refresh") } {
            Invoke-ScpmSync
        }
        { $_ -in @("doctor", "status") } {
            Invoke-ScpmDoctor
        }
        { $_ -in @("update", "upgrade") } {
            Invoke-ScpmUpdate @RemainingArgs
        }
        default {
            # 如果输入的不是已知命令，检查是否是脚本名称或序号
            $reg = Get-ScpmRegistryInternal
            if ($null -ne $reg.scripts -and $reg.scripts.PSObject.Properties.Count -gt 0) {
                $scriptProps = @($reg.scripts.PSObject.Properties)
                $matched = Resolve-ScpmScriptPropsInternal $Subcommand $scriptProps
                if ($matched.Count -gt 0) {
                    Invoke-ScpmInfo $Subcommand
                    return
                }
            }
            Invoke-ScpmHelp $Subcommand
        }
    }
}

# 导出函数与别名
Set-Alias -Name sm -Value scpm -Scope Global
Export-ModuleMember -Function scpm -Alias sm

# --------------------------------------------------------------------
# 自动补全支持 (Argument Completion)
# --------------------------------------------------------------------
try {
    $scriptCompleter = {
        param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

        $elements = $commandAst.CommandElements
        $subcommand = if ($elements.Count -gt 1) { $elements[1].Extent.Text } else { "" }

        if ($elements.Count -eq 2 -and (-not $elements[1].Extent.Text.EndsWith(" "))) {
            $subs = @("init", "ui", "tui", "list", "ls", "toggle", "switch", "manage", "t", "enable", "on", "disable", "off", "info", "show", "methods", "inspect", "add", "new", "edit", "remove", "rm", "sync", "refresh", "doctor", "status", "update", "upgrade", "help", "version")
            $subs | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        } elseif ($subcommand -in @("enable", "on", "disable", "off", "toggle", "t", "switch", "manage", "info", "show", "methods", "inspect", "edit", "remove", "rm")) {
            $reg = Get-ScpmRegistryInternal
            if ($null -ne $reg.scripts) {
                $reg.scripts.PSObject.Properties | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Value.description)
                }
            }
        }
    }

    Register-ArgumentCompleter -CommandName ('scpm', 'sm') -ScriptBlock $scriptCompleter -ErrorAction SilentlyContinue
} catch {}
